using System;
using System.Collections.Generic;
using System.Linq;
using Baseball.Core.Domain;

namespace Baseball.Core.HighSchool
{
    public enum CareerSignatureLegacyRulesVersion { V1=1 }
    public enum CareerSignatureLegacyId { PowerImprint, CommandMap, BreakingTrace, EnduranceRhythm, GamecraftLedger, BatteryPromise }
    public enum CareerSignatureLegacyFamily { Power, Command, Breaking, Endurance, Gamecraft, Battery }
    public sealed class CareerSignatureLegacyEffect
    {
        public CareerSignatureLegacyEffect(int stuff=0,int command=0,int movement=0,int stamina=0){Stuff=stuff;Command=command;Movement=movement;Stamina=stamina;}
        public int Stuff{get;}public int Command{get;}public int Movement{get;}public int Stamina{get;}public int TotalRatingBonus=>Stuff+Command+Movement+Stamina;
        public PitcherSnapshot Applying(PitcherSnapshot p)=>new PitcherSnapshot(p.Id,p.Name,B(p.Stuff+Stuff),B(p.Command+Command),B(p.Movement+Movement),B(p.Stamina+Stamina),p.PitchProfiles,p.ThrowingHand);
        private static int B(int x)=>Math.Min(80,Math.Max(20,x));
    }
    public sealed class CareerSignatureLegacyEvidence
    {
        public CareerSignatureLegacyEvidence(string summary,int? ratingGrowth=null,CareerPerformanceSnapshot performance=null,IReadOnlyList<AwakeningId> selectedAwakenings=null,IReadOnlyList<AwakeningId> matchedAwakenings=null,RelationshipTarget? relationshipTarget=null,int? relationshipTrust=null)
        {Summary=summary;RatingGrowth=ratingGrowth;Performance=performance;SelectedAwakenings=selectedAwakenings??new AwakeningId[0];MatchedAwakenings=matchedAwakenings??new AwakeningId[0];RelationshipTarget=relationshipTarget;RelationshipTrust=relationshipTrust;}
        public string Summary{get;}public int? RatingGrowth{get;}public CareerPerformanceSnapshot Performance{get;}public IReadOnlyList<AwakeningId> SelectedAwakenings{get;}public IReadOnlyList<AwakeningId> MatchedAwakenings{get;}public RelationshipTarget? RelationshipTarget{get;}public int? RelationshipTrust{get;}
    }
    public sealed class CareerSignatureLegacy
    {
        public CareerSignatureLegacy(CareerSignatureLegacyId id,CareerSignatureLegacyFamily family,string title,string detail,CareerSignatureLegacyEffect effect,CareerSignatureLegacyEvidence evidence){Id=id;Family=family;Title=title;Detail=detail;Effect=effect;Evidence=evidence;}
        public CareerSignatureLegacyId Id{get;}public CareerSignatureLegacyFamily Family{get;}public string Title{get;}public string Detail{get;}public CareerSignatureLegacyEffect Effect{get;}public CareerSignatureLegacyEvidence Evidence{get;}
        public static CareerSignatureLegacy Definition(CareerSignatureLegacyId id){var e=new CareerSignatureLegacyEvidence("이 대표 유산의 고정 시작 효과입니다.");switch(id){case CareerSignatureLegacyId.PowerImprint:return L(id,CareerSignatureLegacyFamily.Power,"마운드에 남은 불꽃","강한 공으로 승부한 감각이 다음 투수의 첫 공에 스며듭니다.",new CareerSignatureLegacyEffect(3,stamina:1),e);case CareerSignatureLegacyId.CommandMap:return L(id,CareerSignatureLegacyFamily.Command,"미트 끝의 지도","원하는 곳에 공을 놓던 궤적이 다음 투수의 기준점이 됩니다.",new CareerSignatureLegacyEffect(command:3,movement:1),e);case CareerSignatureLegacyId.BreakingTrace:return L(id,CareerSignatureLegacyFamily.Breaking,"손끝에 남은 궤적","타자 앞에서 공을 꺾던 손끝 감각이 다음 투수에게 이어집니다.",new CareerSignatureLegacyEffect(command:1,movement:3),e);case CareerSignatureLegacyId.EnduranceRhythm:return L(id,CareerSignatureLegacyFamily.Endurance,"긴 이닝의 호흡","끝까지 투구 동작을 지킨 호흡이 다음 투수의 몸에 남습니다.",new CareerSignatureLegacyEffect(stuff:1,stamina:3),e);case CareerSignatureLegacyId.GamecraftLedger:return L(id,CareerSignatureLegacyFamily.Gamecraft,"이닝을 읽는 장부","타자의 노림수와 경기 흐름을 읽은 기록이 다음 투수의 판단을 엽니다.",new CareerSignatureLegacyEffect(command:2,movement:1,stamina:1),e);default:return L(id,CareerSignatureLegacyFamily.Battery,"사인 사이의 약속","포수와 한 공씩 쌓은 믿음이 다음 투수의 침착한 출발을 돕습니다.",new CareerSignatureLegacyEffect(command:2,stamina:2),e);}}
        public static PitcherSnapshot Apply(CareerSignatureLegacyId? id,PitcherSnapshot p)=>id.HasValue?Definition(id.Value).Effect.Applying(p):p;
        public static IReadOnlyList<CareerSignatureLegacy> Candidates(PitcherSnapshot starting,HighSchoolCareerSnapshot state){var growth=new[]{Math.Max(0,state.Pitcher.Stuff-starting.Stuff),Math.Max(0,state.Pitcher.Command-starting.Command),Math.Max(0,state.Pitcher.Movement-starting.Movement),Math.Max(0,state.Pitcher.Stamina-starting.Stamina)};return Enum.GetValues(typeof(CareerSignatureLegacyId)).Cast<CareerSignatureLegacyId>().Select(id=>{var d=Definition(id);return new {Value=L(d.Id,d.Family,d.Title,d.Detail,d.Effect,BuildEvidence(d.Family,growth,state)),Score=Score(d.Family,growth,state)};}).OrderByDescending(x=>x.Score).ThenBy(x=>x.Value.Id.Value()).Take(3).Select(x=>x.Value).ToArray();}
        private static int Score(CareerSignatureLegacyFamily f,int[] g,HighSchoolCareerSnapshot s){var p=s.Performance;var games=p.ImportantGamesCompleted;var m=Matched(f,s.SelectedAwakenings).Count;var c=s.ManagerTrust??s.RelationshipTrust;var k=s.CatcherTrust??s.RelationshipTrust;var r=s.RivalTrust??s.RelationshipTrust;switch(f){case CareerSignatureLegacyFamily.Power:return g[0]*120+p.Strikeouts*12+m*80+r;case CareerSignatureLegacyFamily.Command:return g[1]*120+Math.Max(0,games*3-p.Walks)*18+m*80+c;case CareerSignatureLegacyFamily.Breaking:return g[2]*120+p.Strikeouts*9+m*80+k;case CareerSignatureLegacyFamily.Endurance:return g[3]*120+p.Pitches/2+m*80+c;case CareerSignatureLegacyFamily.Gamecraft:return (g[1]+g[2])*60+Math.Max(0,p.ExpectedDamage-p.ActualDamage)/20+m*80+Math.Max(c,Math.Max(k,r));default:return g[1]*60+Math.Max(0,games*3-p.Walks)*12+m*100+k*2;}}
        private static CareerSignatureLegacyEvidence BuildEvidence(CareerSignatureLegacyFamily f,int[] g,HighSchoolCareerSnapshot s){var p=s.Performance;var rel=Relationship(f,s);var matched=Matched(f,s.SelectedAwakenings);int growth;string lead;switch(f){case CareerSignatureLegacyFamily.Power:growth=g[0];lead="구위 +"+growth+" · "+p.Strikeouts+"탈삼진";break;case CareerSignatureLegacyFamily.Command:growth=g[1];lead="제구 +"+growth+" · "+p.Walks+"볼넷";break;case CareerSignatureLegacyFamily.Breaking:growth=g[2];lead="변화구 +"+growth+" · "+p.Strikeouts+"탈삼진";break;case CareerSignatureLegacyFamily.Endurance:growth=g[3];lead="체력 +"+growth+" · 직접 등판 "+p.Pitches+"구";break;case CareerSignatureLegacyFamily.Gamecraft:growth=g[1]+g[2];lead="제구·변화구 +"+growth+" · 예상 피해 "+p.ExpectedDamage+" / 실제 "+p.ActualDamage;break;default:growth=g[1];lead="제구 +"+growth+" · 포수와 쌓은 믿음 "+rel.Item2;break;}var summary=lead+" · 고교 공식 경기 "+p.ImportantGamesCompleted+"회 · "+(matched.Count==0?"맞닿은 각성 없음":"맞닿은 각성 "+matched.Count+"개")+" · "+rel.Item3+" "+rel.Item2;return new CareerSignatureLegacyEvidence(summary,growth,p,s.SelectedAwakenings,matched,rel.Item1,rel.Item2);}
        private static Tuple<RelationshipTarget,int,string> Relationship(CareerSignatureLegacyFamily f,HighSchoolCareerSnapshot s){var coach=s.ManagerTrust??s.RelationshipTrust;var catcher=s.CatcherTrust??s.RelationshipTrust;var rival=s.RivalTrust??s.RelationshipTrust;if(f==CareerSignatureLegacyFamily.Power)return Tuple.Create(RelationshipTarget.Rival,rival,"라이벌과 쌓은 믿음");if(f==CareerSignatureLegacyFamily.Command||f==CareerSignatureLegacyFamily.Endurance)return Tuple.Create(RelationshipTarget.Coach,coach,"감독과 쌓은 믿음");if(f==CareerSignatureLegacyFamily.Breaking||f==CareerSignatureLegacyFamily.Battery)return Tuple.Create(RelationshipTarget.Catcher,catcher,"포수와 쌓은 믿음");var best=Math.Max(coach,Math.Max(catcher,rival));return best==coach?Tuple.Create(RelationshipTarget.Coach,coach,"감독과 쌓은 믿음"):best==catcher?Tuple.Create(RelationshipTarget.Catcher,catcher,"포수와 쌓은 믿음"):Tuple.Create(RelationshipTarget.Rival,rival,"라이벌과 쌓은 믿음");}
        private static IReadOnlyList<AwakeningId> Matched(CareerSignatureLegacyFamily f,IReadOnlyList<AwakeningId> selected){var sets=new Dictionary<CareerSignatureLegacyFamily,AwakeningId[]>{{CareerSignatureLegacyFamily.Power,new[]{AwakeningId.ExplosiveFastball,AwakeningId.RisingFourSeam}},{CareerSignatureLegacyFamily.Command,new[]{AwakeningId.PinpointEdge,AwakeningId.RepeatableRelease,AwakeningId.FirstPitchStrike,AwakeningId.ScoutComposure}},{CareerSignatureLegacyFamily.Breaking,new[]{AwakeningId.DisappearingBreaker,AwakeningId.SinkerTunnel,AwakeningId.FrozenChangeup,AwakeningId.SweepingSlider,AwakeningId.CurveballClock}},{CareerSignatureLegacyFamily.Endurance,new[]{AwakeningId.IronArm,AwakeningId.LateInningReserve}},{CareerSignatureLegacyFamily.Gamecraft,new[]{AwakeningId.CalmUnderPressure,AwakeningId.PickoffRhythm,AwakeningId.TwoStrikePlan,AwakeningId.TrafficController,AwakeningId.ScoutComposure}},{CareerSignatureLegacyFamily.Battery,new[]{AwakeningId.BatterySync,AwakeningId.PickoffRhythm,AwakeningId.TrafficController}}};return selected.Where(x=>sets[f].Contains(x)).ToArray();}
        private static CareerSignatureLegacy L(CareerSignatureLegacyId id,CareerSignatureLegacyFamily f,string t,string d,CareerSignatureLegacyEffect e,CareerSignatureLegacyEvidence v)=>new CareerSignatureLegacy(id,f,t,d,e,v);
    }
    public static class CareerSignatureLegacyWire { public static string Value(this CareerSignatureLegacyId id){var x=new[]{"power_imprint","command_map","breaking_trace","endurance_rhythm","gamecraft_ledger","battery_promise"};return x[(int)id];} }
}
