using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Baseball.Core.Catalogs;
using Baseball.Core.Domain;
using Baseball.Core.Random;

namespace Baseball.Core.HighSchool
{
    public sealed class HighSchoolCareerEngine
    {
        public const int ArmCautionThreshold=35, ArmWarningThreshold=55, ArmInjuryThreshold=72, ArmFatigueFloor=55, ArmPitchFloor=23, ArmPushThroughRisk=15, ArmRestRelief=45, ArmExamRelief=8;
        public const string ArmCareEventId="evt-arm-care";
        private const int TrainingCompensationPerDeficit=24;
        private static readonly TrainingFocus[] Focuses={TrainingFocus.Velocity,TrainingFocus.Command,TrainingFocus.BreakingBall,TrainingFocus.Stamina,TrainingFocus.Recovery,TrainingFocus.GamePlanning};
        public static readonly IReadOnlyList<string> Regions=new[]{"서울","인천","수원","대전","광주","대구","부산","창원","울산","세종","경기","강원","충북","충남","전북","전남","경북","경남","제주"};
        private static readonly Dictionary<string,string[]> RegionalNames=new Dictionary<string,string[]> {
            {"서울",new[]{"서울덕성고","서울배성고","서울충림고","서울경원고"}},{"인천",new[]{"인천해문결고","인천동림고","인천항성고","인천송해고"}},{"수원",new[]{"수원화성빛고","수원장림고","수원화담결고","수원매화솔고"}},{"대전",new[]{"대전갑천별고","대전들샘결고","대전유진고","대전중원고"}},{"광주",new[]{"광주무등결고","광주예향결고","광주서빛람고","광주무원고"}},{"대구",new[]{"대구팔공결고","대구능금결고","대구달원고","대구청림고"}},{"부산",new[]{"부산해남고","부산항성고","부산항해솔고","부산오륙결고"}},{"창원",new[]{"마산해강고","창원가람솔고","창원누리결고","진해동림고"}},{"울산",new[]{"울산대명고","울산문성고","울산태원고","울산장생고"}},{"세종",new[]{"세종한별고","세종새빛고","세종금빛고","세종연서고"}},{"경기",new[]{"성남유림고","고양서람빛고","시흥소명고","용인청림고"}},{"강원",new[]{"강릉해람고","원주원흥고","춘천호반고","속초설해고"}},{"충북",new[]{"청주직지솔고","청주세명고","충주성문고","진천덕원고"}},{"충남",new[]{"공주금강고","천안능수결고","아산곡교결고","서산해명고"}},{"전북",new[]{"전주한옥솔고","군산새만결고","정읍인원고","익산보석고"}},{"전남",new[]{"화순화원고","순천정원솔고","목포항남고","여수진원고"}},{"경북",new[]{"포항해오름고","경주월림고","구미도원고","안동하회고"}},{"경남",new[]{"마산달빛결고","김해수로결고","양산물빛고","거제푸른섬고"}},{"제주",new[]{"제주한라원고","서귀포해원고","제주탐라빛고","제주오름고"}}
        };
        private static readonly string[][] CoachPools={new[]{"윤태문","강일도","백승관","임동혁","조범석"},new[]{"노재형","한기표","유상민","신정록","곽태윤"},new[]{"오승렬","마동준","채희성","도진광","하병철"},new[]{"배도환","어재원","편상욱","소진철","반석호"}};
        private static readonly string[][] CatcherPools={new[]{"서준호","김도현","박성재","이재영","정우빈"},new[]{"한도윤","송지헌","오세민","권혁준","남기율"},new[]{"차민석","변진서","육정환","구자헌","표재신"},new[]{"문하진","안시후","방준서","석민규","탁이현"}};
        public static readonly IReadOnlyList<CareerChapterSnapshot> Chapters=new[]{
            new CareerChapterSnapshot(1,"낯선 마운드",1,"봄","첫 고교 훈련과 첫 공식 등판이 기다린다"),new CareerChapterSnapshot(2,"첫 번째 증명",1,"여름","여름 대회 출전 명단과 맡을 역할이 정해진다"),new CareerChapterSnapshot(3,"첫 겨울",1,"겨울","봄이 오기 전까지 가장 부족한 한 가지를 다듬는다"),new CareerChapterSnapshot(4,"전국의 시선",2,"봄","전국대회에서 라이벌과 다시 만난다"),new CareerChapterSnapshot(5,"흔들리는 배터리",2,"여름","포수와 자꾸 엇갈리는 사인을 바로잡아야 한다"),new CareerChapterSnapshot(6,"에이스의 책임",2,"가을","피로가 쌓인 채 가을 대회 마운드에 오른다"),new CareerChapterSnapshot(7,"마지막 겨울",2,"겨울","스카우트가 지켜볼 마지막 시즌을 준비한다"),new CareerChapterSnapshot(8,"드래프트 데이",3,"여름","마지막 전국대회를 치르고 드래프트 결과를 기다린다")};
        public static readonly IReadOnlyList<DraftTeamSnapshot> Teams=new[]{
            T("seoul_comets","서울 코메츠",TrainingFocus.Command,72,"2군 선발로 뛰며 원하는 코스에 던지는 능력 향상","차윤호","문재석"),T("busan_marines","부산 블루웨일스",TrainingFocus.Stamina,66,"긴 이닝을 맡는 선발로 훈련","도현우","강태림"),T("incheon_waves","인천 크레스트핀스",TrainingFocus.BreakingBall,70,"결정구 한 종을 프로 수준으로 강화","백승찬","윤도환"),T("daegu_forge","대구 포지",TrainingFocus.Velocity,75,"빠른 직구를 유지하며 불펜으로 빠른 1군 데뷔","신재원","권민철"),T("daejeon_rockets","대전 로켓츠",TrainingFocus.GamePlanning,68,"포수와 구종 순서를 맞추는 선발 훈련","장하준","배성우"),T("gwangju_phoenix","광주 피닉스",TrainingFocus.BreakingBall,64,"직구와 같은 궤도에서 갈라지는 변화구 훈련","서이준","남기석"),T("suwon_guardians","수원 가디언즈",TrainingFocus.Command,61,"볼넷을 줄인 뒤 1군 긴 이닝 구원으로 데뷔","주성민","오태건"),T("changwon_meteors","창원 미티어스",TrainingFocus.Velocity,69,"직구의 움직임과 최고 구속을 함께 향상","류한결","차경호"),T("jeonju_hanok","전주 한울스",TrainingFocus.Stamina,58,"체력을 키워 선발 한 자리에 도전","문시온","신도영"),T("jeju_storm","제주 스톰",TrainingFocus.GamePlanning,63,"기록을 활용해 선발과 구원을 오가는 투수로 훈련","한유찬","조민규")};
        private static readonly RivalSnapshot[] Rivals={new RivalSnapshot("rival-seo","서하준","천재 교타형",47,44,39),new RivalSnapshot("rival-lee","권태오","초구 거포형",42,37,49),new RivalSnapshot("rival-park","남도현","안타 제조형",46,45,37),new RivalSnapshot("rival-kang","배시우","외다리 장타형",39,40,50),new RivalSnapshot("rival-yoon","류건우","장신 호타준족형",44,40,43),new RivalSnapshot("rival-choi","정세현","득점권 해결사형",44,43,48),new RivalSnapshot("rival-home-run","강이안","몸쪽 사냥형",41,44,50),new RivalSnapshot("rival-speed","문재윤","질주형 중심타자",47,40,46)};

        public static IReadOnlyList<SchoolSnapshot> Schools(string region)
        {
            string[] names;if(!RegionalNames.TryGetValue(region,out names))names=RegionalNames["서울"];var ri=Regions.IndexOf(region);if(ri<0)ri=0;
            return new[]{new SchoolSnapshot(SchoolId.HanbitTraditional,names[0],"기본기와 긴 이닝",CoachPools[0][ri%5],"원칙형",CatcherPools[0][ri%5],"안정형",TrainingFocus.Stamina,"새 구종을 시험할 기회가 적습니다.","새벽 반복 훈련을 고집하며 핑계보다 공 하나를 더 던지게 합니다.","재임 14년 · 전국대회 4강 6회","실투 뒤에도 먼저 투수에게 공을 돌려주는 매일 출전형 포수입니다.","중학 마지막 시즌 26경기 · 도루저지율 .438"),new SchoolSnapshot(SchoolId.MiraeAnalytics,names[1],"기록을 활용한 타자 상대법",CoachPools[1][ri%5],"분석형",CatcherPools[1][ri%5],"분석형",TrainingFocus.GamePlanning,"데이터가 적을 때 판단이 흔들릴 수 있습니다."),new SchoolSnapshot(SchoolId.HaedongPower,names[2],"빠른 직구와 공격적인 승부",CoachPools[2][ri%5],"승부형",CatcherPools[2][ri%5],"공격형",TrainingFocus.Velocity,"빠른 공을 많이 던질수록 피로가 쌓이고 제구가 흔들립니다."),new SchoolSnapshot(SchoolId.CheongamDevelopment,names[3],"개인별 투구 동작과 변화구 훈련",CoachPools[3][ri%5],"육성형",CatcherPools[3][ri%5],"공감형",TrainingFocus.BreakingBall,"팀이 연패하면 개인 훈련 시간이 줄어듭니다.")};
        }

        public HighSchoolCareerResult Start(StartHighSchoolCareerParams p)
        {
            var seed=Seed(p.Seed);var preset=PitcherPresetCatalog.All.FirstOrDefault(x=>x.Id==p.PresetId);if(preset==null)throw Invalid("unknown career pitcher preset");if(p.CreationAllocation.Total!=5||p.InheritedMemories.Count>4||p.Karmas.Distinct().Count()!=p.Karmas.Count||p.Karmas.Count>2||string.IsNullOrWhiteSpace(p.Identity.Name)||string.IsNullOrWhiteSpace(p.Identity.Region))throw Invalid("career creation or inherited memories are invalid");
            var careerId="career-"+p.Seed+"-life-"+p.LifeNumber;var talent=TalentRules.Make(careerId);var boosts=new HashSet<SoulBoostId>(p.SoulBoosts??new SoulBoostId[0]);if(boosts.Contains(SoulBoostId.TalentBreak))talent=RaiseLowest(talent);
            var wind=CareerWind.For(careerId,CareerRulesVersion.V2);var pitcher=ApplyCreation(preset.Pitcher,p.CreationAllocation,p.Identity);pitcher=ApplyInheritance(pitcher,p.InheritedSoulTotal??p.InheritedSoulPoints,p.InheritedSoulDomain,p.InheritedMemories,talent,p.InheritanceRulesVersion,boosts.Contains(SoulBoostId.HeadStart)?5:0);pitcher=ApplyKarmas(pitcher,p.Karmas);pitcher=CareerSignatureLegacy.Apply(p.SignatureLegacyId,pitcher);
            var reward=1000+p.Karmas.Sum(x=>x.RewardPermille())+wind.RewardBonusPermille;var state=new HighSchoolCareerSnapshot {CareerId=careerId,Revision=0,LifeNumber=p.LifeNumber,Phase=HighSchoolCareerPhase.Prologue,Identity=p.Identity,Difficulty=p.Difficulty,Karmas=p.Karmas.ToArray(),LegacyRewardPermille=reward,MemorySlots=(p.Karmas.Contains(KarmaId.ErasedMemory)?2:3)+(boosts.Contains(SoulBoostId.ExtraMemory)?1:0),Pitcher=pitcher,SchoolOptions=Schools(p.Identity.Region),School=null,Rival=MakeRival(seed,p.Difficulty.SimulationDifficulty,p.Karmas,wind.RivalBonus),Chapter=Chapters[0],ChapterTrainingCount=0,TotalTrainingsCompleted=0,MilestoneIndex=0,RelationshipsCompleted=0,RelationshipTrust=50,ManagerTrust=50,CatcherTrust=50,RivalTrust=50,SelectedAwakenings=new AwakeningId[0],AwakeningOptions=new AwakeningId[0],Fatigue=5,Performance=new CareerPerformanceSnapshot(),SeasonLog=new ProGameLine[0],News=((wind.NewsLine==null?new string[0]:new[]{wind.NewsLine}).Concat(PrologueNews(p.Identity,p.LifeNumber,p.InheritedMemories.Count))).ToArray(),FanInterest=wind.StartingFanInterest,LegacyOptions=new MemoryCardId[0],SelectedMemories=new MemoryCardId[0],BalanceVersion=PitcherPresetCatalog.BalanceVersion,WorldRulesVersion=2,ArmRisk=0,InjuryRecovery=0,Schedule=MakeSchedule(careerId),Talent=talent,SoulBoosts=boosts.Count==0?null:boosts.Select(x=>x.ToString()).OrderBy(x=>x).ToArray(),AwakeningSparks=null};
            Sign(state);return Result(seed,state,"high_school_career_started");
        }
        public HighSchoolCareerResult CompletePrologue(AdvanceCareerChapterParams p){var seed=Validate(p.Seed,p.State,HighSchoolCareerPhase.Prologue);var s=Next(p.State);s.Phase=HighSchoolCareerPhase.SchoolSelection;s.News=(new[]{"고교 진학 제안 도착 · "+s.Identity.Name+" · "+s.Identity.Region+" 4개 학교"}).Concat(s.News).ToArray();return Finish(seed,s,"middle_school_prologue_completed");}
        public HighSchoolCareerResult ChooseSchool(ChooseSchoolParams p){var seed=Validate(p.Seed,p.State,HighSchoolCareerPhase.SchoolSelection);var options=Schools(p.State.Identity.Region);var school=options.FirstOrDefault(x=>x.Id==p.SchoolId);if(school==null)throw Invalid("school is not available");var s=Next(p.State);s.Phase=HighSchoolCareerPhase.Training;s.SchoolOptions=options;s.School=school;s.TrainingOpportunity=TrainingOpportunity(s.CareerId,0,s.Fatigue,s.InjuryRecovery??0);s.News=(new[]{school.Name+" 입학이 확정됐습니다. "+school.CoachName+" 감독은 첫 훈련부터 ‘"+school.Philosophy+"’을 강조했습니다."}).Concat(s.News).ToArray();return Finish(seed,s,"school_selected",new[]{"school."+school.Id.ToString().ToLowerInvariant()});}

        public TrainingGrowthOutlook TrainingOutlook(HighSchoolCareerSnapshot state,TrainingFocus focus,TrainingIntensity intensity){if((state.InjuryRecovery??0)>0)return TrainingGrowthOutlook.None;var ability=TalentRules.From(focus);var talent=state.Talent??TalentSnapshot.Unlimited;if(Rating(focus,state.Pitcher)>=talent.Grade(ability).Ceiling())return TrainingGrowthOutlook.Wall;var value=TrainingSignalBase(state,focus,intensity,state.TrainingOpportunity!=null&&state.TrainingOpportunity.Focus==focus);var bonus=state.CareerWind.Rules.TrainingGrowthBonus(focus);var lo=TrainingGrowth(Math.Max(60,value-45))+bonus;var hi=TrainingGrowth(Math.Max(60,value+45))+bonus;if(lo>=2)return TrainingGrowthOutlook.Two;if(lo==1&&hi>=2)return TrainingGrowthOutlook.OneOrTwo;if(lo==1)return TrainingGrowthOutlook.One;if(hi==0)return TrainingGrowthOutlook.None;return TrainingGrowthOutlook.ZeroOrOne;}
        public HighSchoolCareerResult CommitTraining(CommitCareerTrainingParams p)
        {
            var seed=Validate(p.Seed,p.State,HighSchoolCareerPhase.Training);var schedule=p.State.Schedule??CareerScheduleSnapshot.FixedDefault;var required=schedule.TrainingsByChapter[p.State.Chapter.Number-1];if(p.State.School==null||p.State.ChapterTrainingCount>=required)throw Invalid("career training is out of order");var number=p.State.TotalTrainingsCompleted+1;var rehab=(p.State.InjuryRecovery??0)>0;var focus=rehab?TrainingFocus.Recovery:p.Focus;var wind=p.State.CareerWind.Rules;var rng=new SplitMix64(seed^(ulong)number^0x434152454552UL);var hit=!rehab&&p.State.TrainingOpportunity!=null&&p.Focus==p.State.TrainingOpportunity.Focus;var signal=Math.Max(60,TrainingSignalBase(p.State,p.Focus,p.Intensity,hit)+rng.NextInt(91)-45);var jackpotChance=p.State.SoulBoosts!=null&&p.State.SoulBoosts.Contains(SoulBoostId.TrainingRhythm.ToString())?26:16;var jackpot=!rehab&&focus!=TrainingFocus.Recovery&&rng.NextInt(100)<jackpotChance;var baseGrowth=rehab||focus==TrainingFocus.Recovery?0:TrainingGrowth(signal);if(baseGrowth==0&&number==1&&p.State.LifeNumber==1&&!rehab&&focus!=TrainingFocus.Recovery)baseGrowth=1;var raw=(jackpot?baseGrowth*2:baseGrowth)+(rehab?0:wind.TrainingGrowthBonus(focus));var before=Rating(focus,p.State.Pitcher);var talent=p.State.Talent??TalentSnapshot.Unlimited;var application=raw>0?TalentRules.Apply(talent,TalentRules.From(p.Focus),Rating(p.Focus,p.State.Pitcher),raw):new TalentApplication(0,talent,null);var target=focus==TrainingFocus.BreakingBall&&((p.State.BalanceVersion??1)>=4)?PitcherGrowthRules.NormalizeBreakingBallTarget(p.TargetPitch,p.State.Pitcher):null;var pitcher=Grow(p.State.Pitcher,p.Focus,application.Allowed,p.State.BalanceVersion,target);var baseFatigue=p.Intensity==TrainingIntensity.Light?3:p.Intensity==TrainingIntensity.Standard?8:15;var fatigue=rehab?Clamp(p.State.Fatigue+wind.TrainingFatigueModifier(TrainingFocus.Recovery)-wind.AdjustedRecovery(24),0,100):Clamp(p.State.Fatigue+baseFatigue+wind.TrainingFatigueModifier(focus)-(p.Focus==TrainingFocus.Recovery?wind.AdjustedRecovery(18):0),0,100);var after=Rating(focus,pitcher);var growth=after-before;var feedback=rehab?"재활 훈련으로 팔 상태를 회복합니다. 이번 훈련은 성장 없이 지나갑니다.":growth>0?(Label(focus)+" 능력치가 "+growth+" 올랐습니다."):"이번 훈련에서는 능력치가 오르지 않았습니다. 피로와 훈련 강도를 조절해 다시 시도할 수 있습니다.";if(jackpot&&growth>0)feedback="대성공! 오늘은 몸이 완전히 열렸습니다. "+feedback;
            var s=Next(p.State);s.Pitcher=pitcher;s.Fatigue=fatigue;s.TotalTrainingsCompleted=number;s.ChapterTrainingCount++;s.LastTraining=new CareerTrainingSnapshot(number,focus,p.Intensity,growth,fatigue-p.State.Fatigue,feedback,before,after,p.State.Fatigue,fatigue,hit,application.Bloomed,application.Bloomed.HasValue?(TalentGrade?)application.Talent.Grade(application.Bloomed.Value):null,jackpot&&growth>0,target);s.Talent=application.Talent;s.InjuryRecovery=rehab?(p.State.InjuryRecovery??0)-1:p.State.InjuryRecovery;s.ArmRisk=rehab?Math.Max(0,(p.State.ArmRisk??0)-10):Clamp((p.State.ArmRisk??0)+(((p.State.BalanceVersion??1)>=4)?TrainingArmRisk(focus,p.Intensity):0),0,100);if(application.Bloomed.HasValue)s.AwakeningSparks=Math.Min(6,(s.AwakeningSparks??0)+1);if(s.ChapterTrainingCount>=required)EnterMilestone(s,seed,0);else{s.Phase=HighSchoolCareerPhase.Training;s.TrainingOpportunity=TrainingOpportunity(s.CareerId,s.TotalTrainingsCompleted,s.Fatigue,s.InjuryRecovery??0);}return Finish(seed,s,rehab?"career_training_rehab":"career_training_completed",new[]{"training."+focus.Value()});
        }

        public HighSchoolTrainingBlockResult CommitTrainingBlock(CommitCareerTrainingBlockParams p)
        {
            if(p==null)throw new ArgumentNullException(nameof(p));
            if(p.MaximumSessions<2||p.MaximumSessions>3)throw Invalid("training block requires two or three sessions");
            Validate(p.Seed,p.State,HighSchoolCareerPhase.Training);
            var startingPitcher=p.State.Pitcher;
            var startingFatigue=p.State.Fatigue;
            var result=(HighSchoolCareerResult)null;
            var seed=p.Seed;
            var state=p.State;
            var completed=0;
            var stop=TrainingBlockStopReason.MaximumSessions;
            var sessions=new List<CareerTrainingSnapshot>();
            while(completed<p.MaximumSessions&&state.Phase==HighSchoolCareerPhase.Training)
            {
                result=CommitTraining(new CommitCareerTrainingParams(seed,state,p.Focus,p.Intensity,p.TargetPitch));
                completed++;
                seed=result.NextSeed;
                state=result.Snapshot;
                sessions.Add(state.LastTraining);
                var reason=TrainingBlockStop(state,p.Focus);
                if(reason.HasValue){stop=reason.Value;break;}
            }
            if(result==null)throw Invalid("training block did not complete a session");
            var growth=RatingTotal(state.Pitcher)-RatingTotal(startingPitcher);
            var block=new CareerTrainingBlockSnapshot(p.MaximumSessions,completed,p.Focus,p.Intensity,
                state.LastTraining==null?null:state.LastTraining.TargetPitch,stop,growth,state.Fatigue-startingFatigue,sessions);
            return new HighSchoolTrainingBlockResult(result,block);
        }

        public HighSchoolCareerResult ResolveRelationship(ResolveCareerRelationshipParams p)
        {
            var seed=Validate(p.Seed,p.State,HighSchoolCareerPhase.Relationship);if(p.State.CurrentRelationshipEvent!=null&&p.State.CurrentRelationshipEvent.Id==ArmCareEventId)return ResolveArmCare(seed,p.State,p.Response);var category=p.State.CurrentRelationshipEvent==null?"coach":p.State.CurrentRelationshipEvent.Category;var target=RelationshipTargetForEventCategory(category);var impact=RelationshipImpact(category,p.Response);var change=p.State.CareerWind.Rules.AdjustedRelationshipTrustChange(impact.Trust,target);if(p.State.Karmas.Contains(KarmaId.StubbornCoach)&&target==RelationshipTarget.Coach)change=change<0?change*2:change/2;var manager=p.State.ManagerTrust??p.State.RelationshipTrust;var catcher=p.State.CatcherTrust??p.State.RelationshipTrust;var rival=p.State.RivalTrust??p.State.RelationshipTrust;var before=target==RelationshipTarget.Coach?manager:target==RelationshipTarget.Catcher?catcher:rival;if(target==RelationshipTarget.Coach)manager=Clamp(manager+change,0,100);else if(target==RelationshipTarget.Catcher)catcher=Clamp(catcher+change,0,100);else rival=Clamp(rival+change,0,100);var fatigue=Clamp(p.State.Fatigue+impact.Fatigue,0,100);var fans=Clamp(p.State.FanInterest+p.State.CareerWind.Rules.AdjustedFanInterestChange(impact.Fans),0,100);var pitcher=p.State.Pitcher;var abilityBefore=impact.Focus.HasValue?(int?)Rating(impact.Focus.Value,pitcher):null;if(impact.Focus.HasValue)pitcher=Grow(pitcher,impact.Focus.Value,1);var abilityAfter=impact.Focus.HasValue?(int?)Rating(impact.Focus.Value,pitcher):null;var s=Next(p.State);s.Pitcher=pitcher;s.RelationshipsCompleted++;s.ManagerTrust=manager;s.CatcherTrust=catcher;s.RivalTrust=rival;s.RelationshipTrust=(manager+catcher+rival)/3;s.Fatigue=fatigue;s.FanInterest=fans;s.LastRelationship=new CareerRelationshipResultSnapshot(s.RelationshipsCompleted,target==RelationshipTarget.Coach?"coach":target==RelationshipTarget.Catcher?"catcher":"rival",p.State.CurrentRelationshipEvent==null?"대화":p.State.CurrentRelationshipEvent.Title,p.Response,before,target==RelationshipTarget.Coach?manager:target==RelationshipTarget.Catcher?catcher:rival,p.State.Fatigue,fatigue,p.State.FanInterest,fans,impact.Focus,abilityBefore,abilityAfter,impact.Text);s.News=(new[]{(p.State.CurrentRelationshipEvent==null?"대화":p.State.CurrentRelationshipEvent.Title)+" — "+impact.Text}).Concat(s.News).ToArray();AdvanceMilestone(s,seed);return Finish(seed,s,"career_relationship_resolved",new[]{"relationship."+p.Response.ToString().ToLowerInvariant()});
        }

        public HighSchoolCareerResult RecordImportantGame(RecordCareerGameParams p)
        {
            var seed=Validate(p.Seed,p.State,HighSchoolCareerPhase.ImportantGame);var expected=p.State.Performance.ImportantGamesCompleted+1;if(p.Report.ScenarioNumber!=expected||p.Report.Pitches<=0||p.Report.RecommendationAccepted<0||p.Report.RecommendationAccepted>p.Report.Pitches)throw Invalid("career important game report is invalid");var growth=CareerGameGrowth.Evaluate(p.State,p.Report);var performance=p.State.Performance.Adding(p.Report);var fans=Clamp(p.State.FanInterest+p.State.CareerWind.Rules.AdjustedFanInterestChange(Math.Max(2,p.Report.Strikeouts*2-p.Report.RunsAllowed*2)),0,100);var risk=Clamp((p.State.ArmRisk??0)+(p.Report.Pitches>ArmPitchFloor?p.Report.Pitches-ArmPitchFloor+Math.Max(0,p.State.Fatigue-ArmFatigueFloor):0),0,100);var spark=Math.Min(6,(p.State.AwakeningSparks??0)+(p.Report.RunsAllowed==0||p.Report.Strikeouts>=4?2:0)+(p.Report.ActualDamage<=p.Report.ExpectedDamage?1:0)+(growth!=null&&growth.BloomedAbility.HasValue?1:0));var rng=new SplitMix64(seed^0x4853504C4159UL);var outs=p.Report.Outs??Math.Min(27,p.Report.Pitches/5);var support=p.Report.TeamRuns??LeagueBaseline.HighSchoolTeamRuns(ref rng);var opponent=p.Report.RunsAllowed+LeagueBaseline.RestOfHighSchoolTeamRuns(Math.Max(0,27-outs),ref rng);var line=new ProGameLine(p.State.Chapter.SchoolYear,p.State.Chapter.Number,(p.State.SeasonLog==null?0:p.State.SeasonLog.Count)+1,false,outs,p.Report.Strikeouts,p.Report.Walks,p.Report.RunsAllowed,p.Report.Pitches,support,opponent,DecisionRules.Decide(false,false,outs,p.Report.RunsAllowed,support,opponent),true,p.Report.Hits,p.Report.HomeRuns);
            var s=Next(p.State);s.Pitcher=growth==null?p.State.Pitcher:growth.Applying(p.State.Pitcher);s.Talent=growth==null?p.State.Talent:growth.ResultingTalent;s.Performance=performance;s.FanInterest=fans;s.ArmRisk=risk;s.AwakeningSparks=spark;s.Fatigue=Clamp(p.State.Fatigue+Math.Max(5,p.Report.Pitches*Math.Max(60,140-p.State.Pitcher.Stamina)/200),0,100);s.SeasonLog=(p.State.SeasonLog??new ProGameLine[0]).Concat(new[]{line}).ToArray();s.News=(new[]{p.Report.RunsAllowed==0?s.Pitcher.Name+", "+s.Rival.Name+"과의 승부에서 무실점":s.Pitcher.Name+", "+p.Report.Strikeouts+"탈삼진 · "+p.Report.Walks+"볼넷 · "+p.Report.RunsAllowed+"실점"}).Concat(s.News).ToArray();AdvanceMilestone(s,seed);return Finish(seed,s,"career_important_game_completed",new[]{"important_game."+expected}.Concat(growth==null?new string[0]:new[]{growth.ReasonCode}).ToArray());
        }
        public HighSchoolCareerResult ChooseAwakening(ChooseCareerAwakeningParams p){var seed=Validate(p.Seed,p.State,HighSchoolCareerPhase.Awakening);if(!p.State.AwakeningOptions.Contains(p.Awakening)||p.State.SelectedAwakenings.Contains(p.Awakening))throw Invalid("career awakening is not available");var s=Next(p.State);s.Pitcher=ApplyAwakening(p.State.Pitcher,p.Awakening);s.SelectedAwakenings=p.State.SelectedAwakenings.Concat(new[]{p.Awakening}).ToArray();s.AwakeningOptions=new AwakeningId[0];s.AwakeningSparks=0;s.News=(new[]{"‘"+AwakeningTitle(p.Awakening)+"’을 익혔습니다."}).Concat(s.News).ToArray();AdvanceMilestone(s,seed);return Finish(seed,s,"career_awakening_selected",new[]{"awakening."+p.Awakening.Value()});}
        public HighSchoolCareerResult AdvanceChapter(AdvanceCareerChapterParams p){var seed=Validate(p.Seed,p.State,HighSchoolCareerPhase.ChapterReview);if(p.State.Chapter.Number>=8)throw Invalid("final chapter cannot advance");var games=SimulateChapterGames(p.State,p.State.Chapter,seed);var s=Next(p.State);s.Phase=HighSchoolCareerPhase.Training;s.Chapter=Chapters[p.State.Chapter.Number];s.ChapterTrainingCount=0;s.MilestoneIndex=0;s.SeasonLog=(p.State.SeasonLog??new ProGameLine[0]).Concat(games).ToArray();s.TrainingOpportunity=TrainingOpportunity(s.CareerId,s.TotalTrainingsCompleted,s.Fatigue,s.InjuryRecovery??0);s.News=(new[]{ChapterGameHeadline(games),s.Chapter.Title+" — "+s.Chapter.Theme+"."}).Concat(s.News).ToArray();return Finish(seed,s,"career_chapter_advanced",new[]{"chapter."+s.Chapter.Number});}

        public static DraftEvaluationComponents DraftEvaluationCore(HighSchoolCareerSnapshot s){var v4=(s.BalanceVersion??1)>=4;var ratings=s.Pitcher.Stuff+s.Pitcher.Command+s.Pitcher.Movement+s.Pitcher.Stamina;var quality=v4?s.Performance.Strikeouts*4-s.Performance.Walks*2-s.Performance.RunsAllowed*2:s.Performance.Strikeouts*3-s.Performance.Walks*2-s.Performance.RunsAllowed*3;var process=Clamp((s.Performance.ExpectedDamage-s.Performance.ActualDamage)/350,-8,10);var auto=(s.SeasonLog??new ProGameLine[0]).Where(x=>!x.Played).ToArray();var outs=auto.Sum(x=>x.Outs);var runs=auto.Sum(x=>x.RunsAllowed);var cap=v4?2:4;var season=outs==0?0:Clamp((HighSchoolBaseline(s.LifeNumber,s.Pitcher.Id,s.BalanceVersion)-runs*27000/outs)*(v4?1:4)/1000,-cap,cap);var risk=s.ArmRisk??0;return new DraftEvaluationComponents(ratings/4+15,quality/(v4?6:4),process,s.SelectedAwakenings.Count,(s.RelationshipTrust-50)/10,season,(s.Karmas.Contains(KarmaId.UnknownLand)?3:0)+(s.Karmas.Contains(KarmaId.NoLastChance)?2:0),risk>=ArmWarningThreshold?4:risk>=45?2:0,Clamp((s.FanInterest-40)/15,-3,3),s.CareerWind.Rules.DraftEvaluationDelta);}
        public static int DraftThreshold(HighSchoolCareerSnapshot s)=>(s.Difficulty.CareerHarshness==DifficultyLevel.Relaxed?57:s.Difficulty.CareerHarshness==DifficultyLevel.Challenging?65:61)+((s.BalanceVersion??1)>=4?5:0);
        public static int DraftVariance(int? balanceVersion,int roll){if((balanceVersion??1)>=4){if(roll<0||roll>=5)throw new ArgumentOutOfRangeException(nameof(roll));return roll==0?-1:roll==4?1:0;}if(roll<0||roll>=11)throw new ArgumentOutOfRangeException(nameof(roll));return roll-5;}
        public static DraftForecastSnapshot DraftForecast(HighSchoolCareerSnapshot s){var score=Clamp(DraftEvaluationCore(s).Total,20,95);var threshold=DraftThreshold(s);var band=score>=78?"1라운드 예상":score>=70?"2~3라운드 예상":score>=threshold+5?"4~6라운드 예상":score>=threshold-5?"당락 경계 — 남은 경기가 정한다":"미지명권 — 아직 명단 밖";return new DraftForecastSnapshot(score,threshold,band,BestTeam(s.Pitcher).Name);}
        public HighSchoolCareerResult ResolveDraft(ResolveDraftParams p){var seed=Validate(p.Seed,p.State,HighSchoolCareerPhase.Draft);var rng=new SplitMix64(seed^0x445241465400UL);var score=Clamp(DraftEvaluationCore(p.State).Total+DraftVariance(p.State.BalanceVersion,rng.NextInt((p.State.BalanceVersion??1)>=4?5:11)),20,95);var drafted=score>=DraftThreshold(p.State);var team=drafted?BestTeam(p.State.Pitcher):null;int? round=drafted?(score>=78?1:score>=70?2:4):(int?)null;int? pick=round.HasValue?(round.Value-1)*10+rng.NextInt(10)+1:(int?)null;var draft=new DraftResultSnapshot(drafted?DraftOutcome.Drafted:DraftOutcome.Undrafted,score,drafted?(score>=78?"1라운드":score>=70?"2~3라운드":"4~6라운드"):"미지명",team,round,pick,round.HasValue?Math.Max(40000000,300000000-round.Value*45000000):(int?)null,team==null?null:"퓨처스 선발 10경기와 볼넷률 8% 이하",new[]{"능력 "+DraftEvaluationCore(p.State).RatingScore,"고교 공식 경기 "+DraftEvaluationCore(p.State).PerformanceScore},drafted?"지명 구단 · "+team.Name+". 구위와 고교 경기 기록에서 높은 평가를 받았습니다.":"마지막 라운드까지 이름이 불리지 않았습니다. 다음 선수에게 남길 기록을 고르세요.");var s=Next(p.State);s.Phase=drafted?HighSchoolCareerPhase.Completed:HighSchoolCareerPhase.Legacy;s.DraftResult=draft;s.LegacyOptions=MemoryOptions(p.State,seed);s.News=(new[]{drafted?"드래프트 지명 · "+team.Name+" · "+s.Pitcher.Name:"드래프트가 끝날 때까지 이름이 불리지 않았습니다."}).Concat(s.News).ToArray();return Finish(seed,s,"career_draft_resolved",new[]{"draft."+(drafted?"drafted":"undrafted")});}
        public HighSchoolCareerResult OpenLegacy(AdvanceCareerChapterParams p){var seed=Validate(p.Seed,p.State,HighSchoolCareerPhase.Completed);if(p.State.DraftResult==null||p.State.DraftResult.Outcome!=DraftOutcome.Drafted)throw Invalid("미지명 선수는 이미 유산을 고르는 단계입니다.");var s=Next(p.State);s.Phase=HighSchoolCareerPhase.Legacy;return Finish(seed,s,"career_legacy_opened",new[]{"legacy.opened"});}
        public HighSchoolCareerResult SelectLegacy(SelectCareerLegacyParams p){var seed=Validate(p.Seed,p.State,HighSchoolCareerPhase.Legacy);var s=Next(p.State);if(p.SignatureLegacyId.HasValue){if(p.MemoryCards.Count!=0)throw Invalid("signature legacy cannot be mixed with career memories");s.SelectedMemories=new MemoryCardId[0];}else{var unique=p.MemoryCards.Distinct().ToArray();if(unique.Length!=p.State.MemorySlots||unique.Any(x=>!p.State.LegacyOptions.Contains(x)))throw Invalid("select the available number of offered career memories");s.SelectedMemories=unique;s.LegacyOptions=unique;}s.Phase=HighSchoolCareerPhase.Completed;return Finish(seed,s,"career_legacy_selected");}

        public static CareerScheduleSnapshot MakeSchedule(string careerId){var rng=new SplitMix64(StableHash.Fnv1A64Value("run_skeleton|"+careerId));var total=12+rng.NextInt(5);var relationships=4+rng.NextInt(3);var games=4+rng.NextInt(3);var trainings=Enumerable.Repeat(1,8).ToArray();var remaining=total-8;while(remaining>0){var candidates=Enumerable.Range(0,8).Where(i=>trainings[i]<3).ToArray();trainings[candidates[rng.NextInt(candidates.Length)]]++;remaining--;}var queues=new List<Tuple<HighSchoolCareerPhase,int>>{Tuple.Create(HighSchoolCareerPhase.Relationship,relationships),Tuple.Create(HighSchoolCareerPhase.ImportantGame,games-1),Tuple.Create(HighSchoolCareerPhase.Awakening,2)};for(var i=queues.Count-1;i>0;i--){var j=rng.NextInt(i+1);var q=queues[i];queues[i]=queues[j];queues[j]=q;}var seq=new List<HighSchoolCareerPhase>();while(queues.Any(x=>x.Item2>0)){for(var i=0;i<queues.Count;i++)if(queues[i].Item2>0){seq.Add(queues[i].Item1);queues[i]=Tuple.Create(queues[i].Item1,queues[i].Item2-1);}}var milestones=Enumerable.Range(0,8).Select(i=>(IReadOnlyList<HighSchoolCareerPhase>)new List<HighSchoolCareerPhase>()).ToArray();var counts=Enumerable.Repeat(seq.Count/7,7).ToArray();var offset=rng.NextInt(7);for(var i=0;i<seq.Count%7;i++)counts[(offset+i)%7]++;var cursor=0;for(var chapter=0;chapter<7;chapter++)for(var i=0;i<counts[chapter]&&cursor<seq.Count;i++)((List<HighSchoolCareerPhase>)milestones[chapter]).Add(seq[cursor++]);milestones[7]=new[]{HighSchoolCareerPhase.Awakening,HighSchoolCareerPhase.ImportantGame};return new CareerScheduleSnapshot(trainings,milestones);}
        public static ArmHealthState ArmHealthStateFor(int? risk,int? recovery){if((recovery??0)>0)return ArmHealthState.Recovering;if((risk??0)>=ArmWarningThreshold)return ArmHealthState.Warning;if((risk??0)>=ArmCautionThreshold)return ArmHealthState.Caution;return ArmHealthState.Normal;}
        public static TrainingOpportunitySnapshot TrainingOpportunity(string careerId,int index,int fatigue=100,int injuryRecovery=0){var seed=StableHash.Fnv1A64Value(careerId+"|opportunity|"+index);var pick=(int)(seed%(ulong)Focuses.Length);var earned=fatigue>=45||injuryRecovery>0;Func<int,int> skip=start=>{var x=start;var steps=0;while(!earned&&Focuses[x]==TrainingFocus.Recovery&&steps<Focuses.Length){x=(x+1)%Focuses.Length;steps++;}return x;};pick=skip(pick);if(index>0){var prior=skip((int)(StableHash.Fnv1A64Value(careerId+"|opportunity|"+(index-1))%(ulong)Focuses.Length));if(pick==prior)pick=skip((pick+1)%Focuses.Length);}var focus=Focuses[pick];return new TrainingOpportunitySnapshot(focus,OpportunityReason(focus));}
        public static RelationshipTarget RelationshipTargetForEventCategory(string category){if(category=="coach")return RelationshipTarget.Coach;if(category=="rival")return RelationshipTarget.Rival;if(category=="catcher"||category=="growth"||category=="game"||category=="awakening"||category=="fan")return RelationshipTarget.Catcher;return RelationshipTarget.Coach;}
        public static int InheritancePointCap(int points,SoulInheritanceRulesVersion version=SoulInheritanceRulesVersion.V1)=>version==SoulInheritanceRulesVersion.V1?Math.Min(20,8+Math.Max(0,points)/60):Math.Min(20,Math.Max(1,(Math.Max(0,points)-20)/4));
        public static int AppliedInheritance(int points,SoulInheritanceRulesVersion version=SoulInheritanceRulesVersion.V1)=>Math.Min(Math.Max(0,points),InheritancePointCap(points,version));
        public static Tuple<int,int> NextInheritanceStep(int points,SoulInheritanceRulesVersion version){var current=AppliedInheritance(points,version);if(current>=20)return null;for(var p=Math.Max(0,points)+1;p<=Math.Max(0,points)+4000;p++){var applied=AppliedInheritance(p,version);if(applied>current)return Tuple.Create(p,applied);}return null;}

        private void EnterMilestone(HighSchoolCareerSnapshot s,ulong seed,int index){s.MilestoneIndex=index;var phases=s.Schedule.MilestonesByChapter[s.Chapter.Number-1];var phase=index<phases.Count?phases[index]:(s.Chapter.Number==8?HighSchoolCareerPhase.Draft:HighSchoolCareerPhase.ChapterReview);s.Phase=phase;s.AwakeningOptions=phase==HighSchoolCareerPhase.Awakening?AwakeningTree.Available(s.SelectedAwakenings,s.AwakeningSparks):new AwakeningId[0];s.CurrentGameScenario=phase==HighSchoolCareerPhase.ImportantGame?GameScenario(s,seed):null;s.CurrentRelationshipEvent=phase==HighSchoolCareerPhase.Relationship?RelationshipEvent(s,seed):null;}
        private void AdvanceMilestone(HighSchoolCareerSnapshot s,ulong seed){EnterMilestone(s,seed,s.MilestoneIndex+1);}
        private CareerEventContent RelationshipEvent(HighSchoolCareerSnapshot s,ulong seed){if(s.RelationshipsCompleted>=3&&ArmHealthStateFor(s.ArmRisk,s.InjuryRecovery)==ArmHealthState.Warning)return new CareerEventContent(ArmCareEventId,"팔 상태 경고","health","최근 등판 뒤 팔이 평소보다 무겁습니다. 트레이너가 오늘 어떻게 할지 묻습니다.");var core=new[]{"coach","catcher","rival"};if(s.RelationshipsCompleted<3){var rng=new SplitMix64(StableHash.Fnv1A64Value("core_order|"+s.CareerId));for(var i=2;i>0;i--){var j=rng.NextInt(i+1);var t=core[i];core[i]=core[j];core[j]=t;}var pool=HighSchoolContentCatalog.Events.Where(x=>x.Category==core[s.RelationshipsCompleted]).ToArray();return pool[(int)(seed%(ulong)pool.Length)];}if(s.LifeNumber>1){var rr=new SplitMix64(StableHash.Fnv1A64Value("rebirth_event|"+s.CareerId+"|"+s.RelationshipsCompleted));if(rr.NextInt(3)==0)return HighSchoolContentCatalog.RebirthEvents[rr.NextInt(HighSchoolContentCatalog.RebirthEvents.Count)];}var extended=HighSchoolContentCatalog.Events.Where(x=>x.Category!="coach"&&x.Category!="catcher"&&x.Category!="rival").ToArray();return extended[(int)(StableHash.Fnv1A64Value("relationship_pool|"+s.CareerId+"|"+s.RelationshipsCompleted)%(ulong)extended.Length)];}
        private ImportantGameScenarioContent GameScenario(HighSchoolCareerSnapshot s,ulong seed){if(s.Chapter.Number==8)return HighSchoolContentCatalog.Scenarios.First(x=>x.Id=="game-one-run");if(s.Chapter.Number==4)return HighSchoolContentCatalog.Scenarios.First(x=>x.Id=="game-national-final");var pool=HighSchoolContentCatalog.Scenarios.Where(x=>x.MinChapter<=1).ToArray();var run=StableHash.Fnv1A64Value("game_scenario|"+s.CareerId);return pool[((int)(run%(ulong)pool.Length)+s.Performance.ImportantGamesCompleted*7)%pool.Length];}
        private HighSchoolCareerResult ResolveArmCare(ulong seed,HighSchoolCareerSnapshot state,RelationshipResponse response){var s=Next(state);var risk=state.ArmRisk??0;if(response==RelationshipResponse.Challenge){risk=Clamp(risk+ArmPushThroughRisk,0,100);s.Fatigue=Clamp(s.Fatigue+4,0,100);if(risk>=ArmInjuryThreshold){s.InjuryRecovery=risk>=92?2:1;risk=50;if(s.Karmas.Contains(KarmaId.NoLastChance))s.Phase=HighSchoolCareerPhase.Draft;}}else if(response==RelationshipResponse.Listen){risk=Math.Max(0,risk-ArmRestRelief);s.Fatigue=Clamp(s.Fatigue-30,0,100);}else{risk=0;s.Fatigue=Clamp(s.Fatigue-ArmExamRelief,0,100);}s.ArmRisk=risk;s.RelationshipsCompleted++;if(s.Phase!=HighSchoolCareerPhase.Draft)AdvanceMilestone(s,seed);return Finish(seed,s,s.InjuryRecovery>0?"career_arm_injury":"career_arm_care");}
        private static IReadOnlyList<ProGameLine> SimulateChapterGames(HighSchoolCareerSnapshot s,CareerChapterSnapshot chapter,ulong seed){var rng=new SplitMix64(seed^0x485347414D45UL);var rows=new List<ProGameLine>();for(var i=0;i<2;i++){var outs=15+rng.NextInt(7);var strikeouts=Math.Max(0,(s.Pitcher.Stuff+s.Pitcher.Movement-55)/12+rng.NextInt(5));var walks=Math.Max(0,4-s.Pitcher.Command/20+rng.NextInt(3));var runs=Math.Max(0,5-(s.Pitcher.Command+s.Pitcher.Movement)/30+rng.NextInt(4)+DifficultyScale.HighSchool(chapter.Number,s.LifeNumber)/2);var support=LeagueBaseline.HighSchoolTeamRuns(ref rng);var opponent=runs+LeagueBaseline.RestOfHighSchoolTeamRuns(27-outs,ref rng);rows.Add(new ProGameLine(chapter.SchoolYear,chapter.Number,(s.SeasonLog==null?0:s.SeasonLog.Count)+i+1,true,outs,strikeouts,walks,runs,outs*5+walks*3,support,opponent,DecisionRules.Decide(true,false,outs,runs,support,opponent),false,Math.Max(0,runs*2+rng.NextInt(5)),0));}return rows;}
        private static string ChapterGameHeadline(IReadOnlyList<ProGameLine> games){var wins=games.Count(x=>x.Decision==PitchingDecision.Win);return "팀 경기 "+games.Count+"차례 등판 · "+games.Sum(x=>x.Outs)/3+"이닝 "+games.Sum(x=>x.Strikeouts)+"탈삼진 "+games.Sum(x=>x.RunsAllowed)+"실점"+(wins>0?" · "+wins+"승":"");}
        private static int HighSchoolBaseline(int life,string id,int? version){var baseline=(version??1)>=4?(id=="pitcher-command"?1900:id=="pitcher-artist"?2700:id=="pitcher-stamina"?2900:4930):2530;var scale=Enumerable.Range(1,8).Sum(ch=>DifficultyScale.HighSchool(ch,life))*100/8;var first=Enumerable.Range(1,8).Sum(ch=>DifficultyScale.HighSchool(ch,1))*100/8;return baseline+432*(scale-first)/100;}
        private static DraftTeamSnapshot BestTeam(PitcherSnapshot p)=>Teams.OrderByDescending(x=>x.Need==TrainingFocus.Velocity?p.Stuff:x.Need==TrainingFocus.BreakingBall?p.Movement:x.Need==TrainingFocus.Stamina?p.Stamina:p.Command).ThenByDescending(x=>x.Demand).First();
        private static IReadOnlyList<MemoryCardId> MemoryOptions(HighSchoolCareerSnapshot s,ulong seed){var all=Enum.GetValues(typeof(MemoryCardId)).Cast<MemoryCardId>().ToList();var rng=new SplitMix64(seed^0x4D454D4F5259UL);for(var i=all.Count-1;i>0;i--){var j=rng.NextInt(i+1);var x=all[i];all[i]=all[j];all[j]=x;}return all.Take(Math.Max(s.MemorySlots,6)).ToArray();}
        private static PitcherSnapshot ApplyCreation(PitcherSnapshot p,CreationAllocationSnapshot a,PlayerIdentitySnapshot identity)=>new PitcherSnapshot(p.Id,identity.Name,Clamp(p.Stuff+a.Stuff,20,80),Clamp(p.Command+a.Command,20,80),Clamp(p.Movement+a.Movement,20,80),Clamp(p.Stamina+a.Stamina,20,80),p.PitchProfiles,identity.ThrowingHand);
        private static PitcherSnapshot ApplyKarmas(PitcherSnapshot p,IReadOnlyList<KarmaId> karmas){if(karmas.Contains(KarmaId.SingleWeapon))return new PitcherSnapshot(p.Id,p.Name,Clamp(p.Stuff+3,20,80),Clamp(p.Command-2,20,80),Clamp(p.Movement-2,20,80),p.Stamina,p.PitchProfiles,p.ThrowingHand);return p;}
        private static PitcherSnapshot ApplyInheritance(PitcherSnapshot p,int points,SoulDomain? domain,IReadOnlyList<MemoryCardId> memories,TalentSnapshot talent,int? version,int bonus){var rules=version==2?SoulInheritanceRulesVersion.V2:SoulInheritanceRulesVersion.V1;var remaining=AppliedInheritance(points,rules)+Math.Max(0,bonus);var value=p;var rotation=new[]{TrainingFocus.Velocity,TrainingFocus.Command,TrainingFocus.BreakingBall,TrainingFocus.Stamina};if(domain.HasValue&&remaining>0){var focus=domain==SoulDomain.Body?TrainingFocus.Velocity:domain==SoulDomain.Technique?TrainingFocus.Command:TrainingFocus.GamePlanning;var share=remaining/2;while(share-->0){value=Grow(value,focus,1);remaining--;}}while(remaining-->0){var focus=rotation.OrderBy(x=>Rating(x,value)).First();value=Grow(value,focus,1);}foreach(var memory in memories){if(memory==MemoryCardId.VelocityBlueprint)value=Tune(value,2,-1,0,0);else if(memory==MemoryCardId.FingertipMemory)value=Tune(value,0,0,2,-1);else if(memory==MemoryCardId.RecoveryRoutine)value=Tune(value,0,0,0,2);else value=Tune(value,0,1,1,0);}return value;}
        private static TalentSnapshot RaiseLowest(TalentSnapshot t){var abilities=Enum.GetValues(typeof(TalentAbility)).Cast<TalentAbility>().OrderBy(x=>t.Grade(x)).ToArray();var a=abilities[0];var next=t.Grade(a).Next();return next.HasValue?t.Replacing(a,next.Value,t.Pressure(a)):t;}
        private static PitcherSnapshot Grow(PitcherSnapshot p,TrainingFocus f,int points,int? balanceVersion=null,PitchType? targetPitch=null){if(points<=0)return p;if((balanceVersion??1)>=4)return PitcherGrowthRules.Grow(p,f,points,targetPitch);return new PitcherSnapshot(p.Id,p.Name,Clamp(p.Stuff+(f==TrainingFocus.Velocity?points:0),20,80),Clamp(p.Command+(f==TrainingFocus.Command||f==TrainingFocus.GamePlanning?points:0),20,80),Clamp(p.Movement+(f==TrainingFocus.BreakingBall?points:0),20,80),Clamp(p.Stamina+(f==TrainingFocus.Stamina||f==TrainingFocus.Recovery?points:0),20,80),p.PitchProfiles,p.ThrowingHand);}
        private static PitcherSnapshot Tune(PitcherSnapshot p,int stuff,int command,int movement,int stamina)=>new PitcherSnapshot(p.Id,p.Name,Clamp(p.Stuff+stuff,20,80),Clamp(p.Command+command,20,80),Clamp(p.Movement+movement,20,80),Clamp(p.Stamina+stamina,20,80),p.PitchProfiles,p.ThrowingHand);
        private static PitcherSnapshot ApplyAwakening(PitcherSnapshot p,AwakeningId a){var branch=AwakeningTree.GetBranch(a);return branch==AwakeningTree.Branch.Power?Tune(p,3,0,0,1):branch==AwakeningTree.Branch.Command?Tune(p,-1,4,0,0):branch==AwakeningTree.Branch.Breaking?Tune(p,0,-1,4,0):Tune(p,0,2,1,1);}
        private static int TrainingSignalBase(HighSchoolCareerSnapshot s,TrainingFocus f,TrainingIntensity i,bool hit){var basis=i==TrainingIntensity.Light?130:i==TrainingIntensity.Standard?210:280;return basis+(s.School!=null&&s.School.Strength==f?110:0)+(hit?90:0)-Math.Max(0,s.Fatigue-45)*3+Math.Max(0,16-(s.Schedule??CareerScheduleSnapshot.FixedDefault).TrainingTotal)*TrainingCompensationPerDeficit;}
        private static int TrainingGrowth(int signal)=>signal>=430?2:signal>=260?1:0;
        private static int TrainingArmRisk(TrainingFocus focus,TrainingIntensity intensity){if(intensity!=TrainingIntensity.Intensive)return 0;return focus==TrainingFocus.Velocity?3:focus==TrainingFocus.BreakingBall?2:focus==TrainingFocus.Stamina?1:0;}
        private static TrainingBlockStopReason? TrainingBlockStop(HighSchoolCareerSnapshot state,TrainingFocus focus)
        {
            if(state.Phase!=HighSchoolCareerPhase.Training)
            {
                if(state.Phase==HighSchoolCareerPhase.Relationship)return TrainingBlockStopReason.Relationship;
                if(state.Phase==HighSchoolCareerPhase.Awakening)return TrainingBlockStopReason.Awakening;
                if(state.Phase==HighSchoolCareerPhase.ImportantGame)return TrainingBlockStopReason.ImportantGame;
                return TrainingBlockStopReason.PhaseChanged;
            }
            if(state.LastTraining!=null&&state.LastTraining.BloomedAbility.HasValue)return TrainingBlockStopReason.TalentBloom;
            if(focus!=TrainingFocus.Recovery&&state.Fatigue>=75)return TrainingBlockStopReason.Fatigue;
            if(focus!=TrainingFocus.Recovery&&ArmHealthStateFor(state.ArmRisk,state.InjuryRecovery)!=ArmHealthState.Normal)return TrainingBlockStopReason.ArmHealth;
            return null;
        }
        private static int RatingTotal(PitcherSnapshot p)=>p.Stuff+p.Command+p.Movement+p.Stamina;
        private static int Rating(TrainingFocus f,PitcherSnapshot p)=>f==TrainingFocus.Velocity?p.Stuff:f==TrainingFocus.BreakingBall?p.Movement:f==TrainingFocus.Stamina||f==TrainingFocus.Recovery?p.Stamina:p.Command;
        private static string Label(TrainingFocus f)=>f==TrainingFocus.Velocity?"구위":f==TrainingFocus.Command?"제구":f==TrainingFocus.BreakingBall?"변화구":f==TrainingFocus.GamePlanning?"타자 상대법과 제구":"체력";
        private static string AwakeningTitle(AwakeningId a)=>a==AwakeningId.ExplosiveFastball?"폭발하는 포심":a==AwakeningId.PinpointEdge?"바늘끝 제구":a==AwakeningId.DisappearingBreaker?"사라지는 변화구":a.ToString();
        private static string OpportunityReason(TrainingFocus f)=>f==TrainingFocus.Velocity?"릴리스가 빨라졌습니다 — 오늘은 강한 공이 붙는 날입니다.":f==TrainingFocus.Command?"미트가 평소보다 크게 보입니다 — 코스를 다듬을 기회입니다.":f==TrainingFocus.BreakingBall?"손끝 감각이 선명합니다 — 변화구를 만질 날입니다.":f==TrainingFocus.Stamina?"하체가 가볍습니다 — 긴 이닝의 몸을 만들 기회입니다.":f==TrainingFocus.Recovery?"팔이 무겁다는 신호입니다 — 오늘은 회복이 최고의 훈련입니다.":"포수와 읽은 타자 습관이 남아 있습니다 — 경기 계획을 정리할 날입니다.";
        private sealed class Impact { public Impact(int trust,int fatigue,int fans,TrainingFocus? focus,string text){Trust=trust;Fatigue=fatigue;Fans=fans;Focus=focus;Text=text;}public int Trust;public int Fatigue;public int Fans;public TrainingFocus? Focus;public string Text; }
        private static Impact RelationshipImpact(string category,RelationshipResponse response){if(category=="rival")return response==RelationshipResponse.Challenge?new Impact(-1,2,7,TrainingFocus.BreakingBall,"다음 맞대결이 대회에서 가장 기대되는 승부가 됐습니다."):new Impact(3,0,1,TrainingFocus.GamePlanning,"상대가 읽은 반복 습관 하나를 알아냈습니다.");if(category=="health")return response==RelationshipResponse.Listen?new Impact(5,-6,0,null,"오늘은 공을 놓고 회복에 집중하기로 했습니다."):new Impact(-3,6,1,null,"쉬라는 말을 미루고 던졌지만 피로가 더 쌓였습니다.");if(category=="catcher")return response==RelationshipResponse.Listen?new Impact(4,0,0,null,"상대의 말을 끝까지 듣고 다음 준비 기준을 함께 확인했습니다."):response==RelationshipResponse.Explain?new Impact(8,0,0,TrainingFocus.GamePlanning,"두 사람이 본 근거를 합쳐 다음 경기의 구종 순서를 만들었습니다."):new Impact(-4,2,2,TrainingFocus.BreakingBall,"시험은 받아들였지만 포수의 불안은 남았습니다.");if(category=="coach")return response==RelationshipResponse.Listen?new Impact(4,0,0,null,"상대의 말을 끝까지 듣고 다음 준비 기준을 함께 확인했습니다."):response==RelationshipResponse.Explain?new Impact(7,0,0,TrainingFocus.Command,"몸 상태에 맞춰 훈련 강도를 다시 조정했습니다."):new Impact(-4,4,2,TrainingFocus.Velocity,"추가 테스트는 얻었지만 준비 과정을 설득하지 못했습니다.");return response==RelationshipResponse.Listen?new Impact(4,-2,1,null,"이번 일을 차분히 받아들였습니다."):response==RelationshipResponse.Explain?new Impact(3,0,2,TrainingFocus.GamePlanning,"선택의 이유를 기록으로 설명했습니다."):new Impact(1,3,3,TrainingFocus.Velocity,"결과로 답하기로 했습니다.");}
        private static string[] PrologueNews(PlayerIdentitySnapshot id,int life,int memories){if(life<2)return new[]{id.Region+" 중학교 마지막 대회에서 보여준 공이 같은 지역 네 고교의 관심을 끌었습니다."};var openers=new[]{id.Region+" 중학교 마지막 대회. 처음 서는 마운드인데 흙의 감촉이 낯설지 않았습니다. 같은 지역 네 고교가 다시 지켜보고 있습니다.",id.Region+" 중학교 마지막 대회에서 던진 마지막 공. 포수 미트에 꽂히는 소리가 어딘가 익숙했습니다. 네 고교의 시선이 모입니다.",id.Region+" 중학교 마지막 대회를 마친 뒤, 어깨보다 먼저 마음이 다음 이닝을 준비하고 있었습니다. 네 고교에서 제안이 도착했습니다."};return memories>0?new[]{openers[(life-2)%3],"처음 잡는 그립인데 손끝이 먼저 기억합니다 · 설명하기 어려운 감각 "+memories+"가지"}:new[]{openers[(life-2)%3]};}
        private static DraftTeamSnapshot T(string id,string name,TrainingFocus need,int demand,string plan,string competitor,string coach)=>new DraftTeamSnapshot(id,name,need,demand,plan,competitor,coach);
        private static HighSchoolCareerSnapshot Next(HighSchoolCareerSnapshot s){var n=s.Clone();n.Revision++;return n;}
        private static void Sign(HighSchoolCareerSnapshot s)
        {
            var ratings=s.Pitcher.Stuff+":"+s.Pitcher.Command+":"+s.Pitcher.Movement+":"+s.Pitcher.Stamina;
            var perf=s.Performance.ImportantGamesCompleted+":"+s.Performance.Pitches+":"+s.Performance.Strikeouts+":"+s.Performance.Walks+":"+s.Performance.RunsAllowed+":"+s.Performance.ExpectedDamage+":"+s.Performance.ActualDamage;
            var draft=s.DraftResult==null?"none":(s.DraftResult.Outcome==DraftOutcome.Drafted?"drafted":"undrafted")+":"+s.DraftResult.EvaluationScore+":"+(s.DraftResult.Team==null?"none":s.DraftResult.Team.Id);
            var canonical=new List<string>{
                s.CareerId,s.Revision.ToString(CultureInfo.InvariantCulture),s.Phase.Value(),
                s.Identity.Name,s.Identity.ThrowingHand==ThrowingHand.Right?"right":"left",BodyValue(s.Identity.BodyType),s.Identity.Region,
                s.School==null?"none":SchoolValue(s.School.Id),
                DifficultyValue(s.Difficulty.CareerHarshness),DifficultyValue(s.Difficulty.InformationClarity),DifficultyValue(s.Difficulty.SimulationDifficulty),AssistValue(s.Difficulty.InterventionAssist),
                string.Join(",",s.Karmas.Select(KarmaValue)),s.LegacyRewardPermille.ToString(),s.MemorySlots.ToString(),
                s.Chapter.Number.ToString(),s.ChapterTrainingCount.ToString(),s.TotalTrainingsCompleted.ToString(),s.MilestoneIndex.ToString(),s.RelationshipsCompleted.ToString(),s.RelationshipTrust.ToString(),
                string.Join(",",s.SelectedAwakenings.Select(x=>x.Value())),string.Join(",",s.AwakeningOptions.Select(x=>x.Value())),
                s.Fatigue.ToString(),ratings,perf,s.CurrentGameScenario==null?"none":s.CurrentGameScenario.Id,draft,
                string.Join(",",s.LegacyOptions.Select(x=>x.Value())),string.Join(",",s.SelectedMemories.Select(x=>x.Value()))
            };
            if(s.RivalTrust.HasValue)canonical.Add("relationships:"+(s.ManagerTrust??s.RelationshipTrust)+":"+(s.CatcherTrust??s.RelationshipTrust)+":"+(s.RivalTrust??s.RelationshipTrust));
            else if(s.ManagerTrust.HasValue||s.CatcherTrust.HasValue)canonical.Add("staff:"+(s.ManagerTrust??s.RelationshipTrust)+":"+(s.CatcherTrust??s.RelationshipTrust));
            if(s.BalanceVersion.HasValue)canonical.Add("balance_version:"+s.BalanceVersion.Value);
            if(s.WorldRulesVersion.HasValue)canonical.Add("world_rules_version:"+s.WorldRulesVersion.Value);
            if(s.ArmRisk.HasValue)canonical.Add("arm_risk:"+s.ArmRisk.Value);
            if(s.InjuryRecovery.HasValue)canonical.Add("injury_recovery:"+s.InjuryRecovery.Value);
            if(s.AwakeningSparks.HasValue)canonical.Add("awakening_sparks:"+s.AwakeningSparks.Value);
            if(s.SoulBoosts!=null&&s.SoulBoosts.Count>0)canonical.Add("soul_boosts:"+string.Join(",",s.SoulBoosts));
            if(s.Schedule!=null)canonical.Add("schedule:"+s.Schedule.CommitmentToken);
            if(s.LastRelationship!=null){var r=s.LastRelationship;canonical.Add(string.Join(":",new[]{"last_relationship",r.Number.ToString(),r.Category,r.Title,r.Response==RelationshipResponse.Listen?"listen":r.Response==RelationshipResponse.Explain?"explain":"challenge",r.TrustBefore.ToString(),r.TrustAfter.ToString(),r.FatigueBefore.ToString(),r.FatigueAfter.ToString(),r.FanInterestBefore.ToString(),r.FanInterestAfter.ToString(),r.GrowthFocus.HasValue?r.GrowthFocus.Value.Value():"none",r.AbilityBefore.HasValue?r.AbilityBefore.Value.ToString():"none",r.AbilityAfter.HasValue?r.AbilityAfter.Value.ToString():"none",r.Feedback,"current_fan_interest",s.FanInterest.ToString()}));}
            s.StateCommitment=StableHash.Fnv1A64(string.Join("|",canonical));
        }
        private static string BodyValue(BodyType value)=>value==BodyType.Compact?"compact":value==BodyType.Tall?"tall":"balanced";
        private static string DifficultyValue(DifficultyLevel value)=>value==DifficultyLevel.Relaxed?"relaxed":value==DifficultyLevel.Challenging?"challenging":"standard";
        private static string AssistValue(InterventionAssist value)=>value==InterventionAssist.Full?"full":value==InterventionAssist.Minimal?"minimal":"standard";
        private static string SchoolValue(SchoolId value)=>value==SchoolId.HanbitTraditional?"hanbit_traditional":value==SchoolId.MiraeAnalytics?"mirae_analytics":value==SchoolId.HaedongPower?"haedong_power":"cheongam_development";
        private static string KarmaValue(KarmaId value){switch(value){case KarmaId.UnknownLand:return "unknown_land";case KarmaId.StubbornCoach:return "stubborn_coach";case KarmaId.SingleWeapon:return "single_weapon";case KarmaId.GeniusGeneration:return "genius_generation";case KarmaId.ErasedMemory:return "erased_memory";default:return "no_last_chance";}}
        private static HighSchoolCareerResult Finish(ulong seed,HighSchoolCareerSnapshot s,string evt,IReadOnlyList<string> reasons=null){Sign(s);return Result(seed,s,evt,reasons);}
        private static HighSchoolCareerResult Result(ulong seed,HighSchoolCareerSnapshot s,string evt,IReadOnlyList<string> reasons=null){var rng=new SplitMix64(seed^s.Revision^0x4556454E5400UL);var next=rng.Next().ToString(CultureInfo.InvariantCulture);var events=new[]{new HighSchoolCareerEvent(evt,0,reasons)};var hash=StableHash.Fnv1A64(s.CareerId+"|"+s.Revision+"|"+evt+"|"+next+"|"+s.StateCommitment);return new HighSchoolCareerResult(s.Revision,next,events,s,hash);}
        private static ulong Validate(string seed,HighSchoolCareerSnapshot s,HighSchoolCareerPhase phase){var value=Seed(seed);if(s==null||s.Phase!=phase||string.IsNullOrEmpty(s.StateCommitment))throw Invalid("career state or phase is invalid");var copy=s.Clone();Sign(copy);if(copy.StateCommitment!=s.StateCommitment)throw Invalid("career state or phase is invalid");return value;}
        private static ulong Seed(string text){ulong value;if(!ulong.TryParse(text,NumberStyles.None,CultureInfo.InvariantCulture,out value))throw new SimulationException(SimulationErrorCode.InvalidSeed,"invalid seed: "+text);return value;}
        private static SimulationException Invalid(string text)=>new SimulationException(SimulationErrorCode.InvalidGameState,text);
        private static RivalSnapshot MakeRival(ulong seed,DifficultyLevel level,IReadOnlyList<KarmaId> karmas,int wind){var rng=new SplitMix64(seed^0x524956414C00UL);var b=Rivals[rng.NextInt(Rivals.Length)];var bonus=(level==DifficultyLevel.Relaxed?-3:level==DifficultyLevel.Challenging?4:0)+(karmas.Contains(KarmaId.GeniusGeneration)?4:0)+wind;return new RivalSnapshot(b.Id,b.Name,b.Archetype,Clamp(b.Contact+bonus,20,80),Clamp(b.Discipline+bonus,20,80),Clamp(b.Power+bonus,20,80),b.Personality,b.SignatureRecord);}
        private static int Clamp(int value,int min,int max)=>Math.Min(max,Math.Max(min,value));
    }
    internal static class HighSchoolListExtensions { public static int IndexOf<T>(this IReadOnlyList<T> values,T item){for(var i=0;i<values.Count;i++)if(EqualityComparer<T>.Default.Equals(values[i],item))return i;return -1;} }
}
