using System;
using System.Collections.Generic;
using System.Linq;
using Baseball.Core.Domain;
using Baseball.Core.Random;

namespace Baseball.Core.HighSchool
{
    public static class LeagueTable
    {
        public const int GamesPerSeason=144, WeeksPerSeason=24;
        public sealed class StandingRow { public StandingRow(string teamId,string teamName,int wins,int losses,int draws){TeamId=teamId;TeamName=teamName;Wins=wins;Losses=losses;Draws=draws;} public string TeamId{get;}public string TeamName{get;}public int Wins{get;}public int Losses{get;}public int Draws{get;}public int Games=>Wins+Losses+Draws;public double? WinRate=>PitchingMetrics.WinRate(Wins,Losses); }
        public sealed class PlayerGameResult { public PlayerGameResult(int teamRuns,int opponentRuns){TeamRuns=teamRuns;OpponentRuns=opponentRuns;}public int TeamRuns{get;}public int OpponentRuns{get;}public bool? Won=>TeamRuns==OpponentRuns?(bool?)null:TeamRuns>OpponentRuns; }
        public static double GamesBehind(StandingRow row,StandingRow leader)=>((leader.Wins-row.Wins)+(row.Losses-leader.Losses))/2.0;
        public static IReadOnlyList<StandingRow> Standings(int season,string seed,int gamesPlayed,string playerTeamId=null,IReadOnlyList<PlayerGameResult> playerResults=null)
        {
            var played=Math.Min(GamesPerSeason,Math.Max(0,gamesPlayed));var teams=HighSchoolCareerEngine.Teams;if(played==0)return teams.Select(t=>new StandingRow(t.Id,t.Name,0,0,0)).ToArray();
            var rng=new SplitMix64(StableHash.Fnv1A64Value("league|"+seed+"|"+season)^(ulong)season);var strengths=teams.Select(t=>380+rng.NextInt(241)).ToArray();var mean=strengths.Sum()/strengths.Length;for(var i=0;i<strengths.Length;i++)strengths[i]=strengths[i]-mean+500;var draws=teams.Select(t=>(2+rng.NextInt(4))*played/GamesPerSeason).ToArray();if((played*teams.Count-draws.Sum())%2!=0)draws[0]++;
            var rows=new List<StandingRow>();var winTotal=0;for(var i=0;i<teams.Count;i++){var decided=played-draws[i];var wins=Math.Min(decided,Math.Max(0,decided*strengths[i]/1000+rng.NextInt(7)-3));winTotal+=wins;rows.Add(new StandingRow(teams[i].Id,teams[i].Name,wins,decided-wins,draws[i]));}
            if(playerTeamId!=null&&playerResults!=null&&playerResults.Count>0){var index=rows.FindIndex(x=>x.TeamId==playerTeamId);if(index>=0){var old=rows[index];var mine=playerResults.Take(played).ToArray();var mw=mine.Count(x=>x.Won==true);var ml=mine.Count(x=>x.Won==false);var md=mine.Length-mw-ml;var remaining=Math.Max(0,played-mine.Length);var sw=old.Wins*remaining/Math.Max(1,played);var sd=Math.Min(remaining-Math.Min(remaining,sw),old.Draws*remaining/Math.Max(1,played));var sl=Math.Max(0,remaining-sw-sd);winTotal+=mw+sw-old.Wins;rows[index]=new StandingRow(old.TeamId,old.TeamName,mw+sw,ml+sl,md+sd);}}
            return Balanced(rows,winTotal,playerTeamId).OrderByDescending(x=>x.WinRate??0).ThenByDescending(x=>x.Wins).ToArray();
        }
        private static List<StandingRow> Balanced(List<StandingRow> rows,int winTotal,string pinned){var surplus=winTotal-rows.Sum(x=>x.Losses);if(surplus==0)return rows;var order=Enumerable.Range(0,rows.Count).Where(i=>rows[i].TeamId!=pinned).OrderBy(i=>surplus>0?-rows[i].Wins:rows[i].Wins).ToArray();if(surplus%2!=0){foreach(var i in order){var r=rows[i];if(surplus>0&&r.Wins>0){rows[i]=new StandingRow(r.TeamId,r.TeamName,r.Wins-1,r.Losses,r.Draws+1);surplus--;break;}if(surplus<0&&r.Losses>0){rows[i]=new StandingRow(r.TeamId,r.TeamName,r.Wins,r.Losses-1,r.Draws+1);surplus++;break;}}}if(surplus%2!=0)return rows;var n=0;var stalled=0;while(surplus!=0&&stalled<order.Length){var i=order[n++%order.Length];var r=rows[i];if(surplus>0&&r.Wins>0){rows[i]=new StandingRow(r.TeamId,r.TeamName,r.Wins-1,r.Losses+1,r.Draws);surplus-=2;stalled=0;}else if(surplus<0&&r.Losses>0){rows[i]=new StandingRow(r.TeamId,r.TeamName,r.Wins+1,r.Losses-1,r.Draws);surplus+=2;stalled=0;}else stalled++;}return rows;}
        public enum PitcherSort { RunsPer9, Strikeouts, Wins, Whip }
        public sealed class PitcherRow { public PitcherRow(string name,string teamName,int inningsOuts,int wins,int losses,int saves,int strikeouts,int walks,int hits,int homeRuns,int runsAllowed,bool isPlayer=false){Name=name;TeamName=teamName;InningsOuts=inningsOuts;Wins=wins;Losses=losses;Saves=saves;Strikeouts=strikeouts;Walks=walks;Hits=hits;HomeRuns=homeRuns;RunsAllowed=runsAllowed;IsPlayer=isPlayer;}public string Name{get;}public string TeamName{get;}public int InningsOuts{get;}public int Wins{get;}public int Losses{get;}public int Saves{get;}public int Strikeouts{get;}public int Walks{get;}public int Hits{get;}public int HomeRuns{get;}public int RunsAllowed{get;}public bool IsPlayer{get;}public double? RunsPer9=>PitchingMetrics.RunsPer9(RunsAllowed,InningsOuts);public double? Whip=>PitchingMetrics.Whip(Hits,Walks,InningsOuts);}
        public static IReadOnlyList<PitcherRow> Pitchers(int season,string seed,int gamesPlayed,PitcherRow player=null,PitcherSort sort=PitcherSort.RunsPer9){var played=Math.Min(GamesPerSeason,Math.Max(0,gamesPlayed));var rng=new SplitMix64(StableHash.Fnv1A64Value("leaders|"+seed+"|"+season)^(ulong)(season*31));var rows=new List<PitcherRow>();foreach(var team in HighSchoolCareerEngine.Teams)for(var slot=0;slot<2;slot++){var outs=432*(75+rng.NextInt(41))/100*played/GamesPerSeason;if(outs<30)continue;var inn=outs/3.0;var ra9=2.2+rng.NextInt(260)/100.0;var k9=6.5+rng.NextInt(550)/100.0;var bb9=1.2+rng.NextInt(300)/100.0;var h9=7+rng.NextInt(350)/100.0;var hr9=.4+rng.NextInt(110)/100.0;var runs=(int)Math.Round(ra9*inn/9,MidpointRounding.AwayFromZero);var dec=Math.Max(1,outs/54);var share=Math.Max(20,Math.Min(80,50+(int)((3.5-ra9)*22)));var wins=dec*share/100+rng.NextInt(3)-1;rows.Add(new PitcherRow(PitcherName(ref rng),team.Name,outs,Math.Max(0,wins),Math.Max(0,dec-Math.Max(0,wins)),0,(int)Math.Round(k9*inn/9),(int)Math.Round(bb9*inn/9),(int)Math.Round(h9*inn/9),(int)Math.Round(hr9*inn/9),runs));}if(player!=null)rows.Add(player);return Sorted(rows,sort);}
        public static IReadOnlyList<PitcherRow> Sorted(IEnumerable<PitcherRow> rows,PitcherSort sort){switch(sort){case PitcherSort.Strikeouts:return rows.OrderByDescending(x=>x.Strikeouts).ToArray();case PitcherSort.Wins:return rows.OrderByDescending(x=>x.Wins).ToArray();case PitcherSort.Whip:return rows.OrderBy(x=>x.Whip??double.MaxValue).ToArray();default:return rows.OrderBy(x=>x.RunsPer9??double.MaxValue).ToArray();}}
        public static int GamesPlayed(int week)=>Math.Min(GamesPerSeason,Math.Max(0,week)*GamesPerSeason/WeeksPerSeason);
        private static string PitcherName(ref SplitMix64 rng){var s=new[]{"김","이","박","최","정","강","조","윤","장","임","한","오","서","신","권","황"};var g=new[]{"도현","지훈","성민","우진","재원","하준","시우","건우","예준","선우","태윤","민석","현우","정후","승현","주환"};return s[rng.NextInt(s.Length)]+g[rng.NextInt(g.Length)];}
    }
}
