import Foundation

/// Rebirth-loop, archive, pledge, and player-voice copy shared by the high-school meta surfaces.
enum LegacyUICopyKey: String, CaseIterable, Sendable {
    case careerErrorTitle = "legacy.career-error.title"
    case careerErrorBody = "legacy.career-error.body"
    case careerErrorRetry = "legacy.career-error.retry"
    case careerErrorRestart = "legacy.career-error.restart"
    case careerErrorResetTitle = "legacy.career-error.reset.title"
    case careerErrorResetConfirm = "legacy.career-error.reset.confirm"
    case careerErrorResetCancel = "legacy.career-error.reset.cancel"
    case careerErrorResetMessage = "legacy.career-error.reset.message"

    case pledgeDashboardTitle = "legacy.pledge.dashboard-title"
    case pledgeCardTitle = "legacy.pledge.card-title"
    case pledgeIntroFirst = "legacy.pledge.intro.first"
    case pledgeIntroRepeat = "legacy.pledge.intro.repeat"
    case pledgeHint = "legacy.pledge.hint"
    case pledgeCarried = "legacy.pledge.carried"
    case pledgeTierSafe = "legacy.pledge.tier.safe"
    case pledgeTierBold = "legacy.pledge.tier.bold"
    case pledgeTierLegendary = "legacy.pledge.tier.legendary"
    case pledgeReward = "legacy.pledge.reward"
    case pledgeChoose = "legacy.pledge.choose"
    case pledgeSkip = "legacy.pledge.skip"
    case pledgeProgress = "legacy.pledge.progress"
    case pledgeAccessibility = "legacy.pledge.accessibility"
    case pledgeAccessibilityCarried = "legacy.pledge.accessibility.carried"
    case pledgeAlignmentControl = "legacy.pledge.alignment.control"
    case pledgeAlignmentEvaluation = "legacy.pledge.alignment.evaluation"
    case pledgeAlignmentPower = "legacy.pledge.alignment.power"
    case pledgeAlignmentRelationship = "legacy.pledge.alignment.relationship"
    case pledgeAlignmentHealth = "legacy.pledge.alignment.health"
    case pledgeAlignmentFans = "legacy.pledge.alignment.fans"
    case pledgeAlignmentCurrent = "legacy.pledge.alignment.current"
    case pledgeAlignmentSafe = "legacy.pledge.alignment.safe"
    case pledgeAlignmentBold = "legacy.pledge.alignment.bold"
    case pledgeAlignmentLegendary = "legacy.pledge.alignment.legendary"

    case trainingTally = "legacy.training.tally"
    case evaluationPoints = "legacy.evaluation.points"

    case bloomTitle = "legacy.bloom.title"
    case bloomCeiling = "legacy.bloom.ceiling"
    case bloomDismiss = "legacy.bloom.dismiss"
    case bloomAccessibility = "legacy.bloom.accessibility"
    case bloomMeaningD = "legacy.bloom.meaning.d"
    case bloomMeaningC = "legacy.bloom.meaning.c"
    case bloomMeaningB = "legacy.bloom.meaning.b"
    case bloomMeaningA = "legacy.bloom.meaning.a"
    case bloomMeaningS = "legacy.bloom.meaning.s"

    case highlightHomeRunTitle = "legacy.highlight.home-run.title"
    case highlightStrikeoutTitle = "legacy.highlight.strikeout.title"
    case highlightShutdownTitle = "legacy.highlight.shutdown.title"
    case highlightVelocityTitle = "legacy.highlight.velocity.title"
    case highlightInningEndingSubtitle = "legacy.highlight.inning-ending.subtitle"
    case highlightStreakSubtitle = "legacy.highlight.streak.subtitle"
    case highlightShutdownSubtitle = "legacy.highlight.shutdown.subtitle"
    case highlightVelocitySubtitle = "legacy.highlight.velocity.subtitle"

    case highSchoolSummaryCueSetback = "legacy.high-school-summary.cue.setback"
    case highSchoolSummaryCueGrowth = "legacy.high-school-summary.cue.growth"
    case highSchoolSummaryCueSuccess = "legacy.high-school-summary.cue.success"
    case highSchoolSummaryCueNeutral = "legacy.high-school-summary.cue.neutral"
    case highSchoolSummaryFixture = "legacy.high-school-summary.fixture"
    case highSchoolSummaryBackupRecovered = "legacy.high-school-summary.backup-recovered"
    case highSchoolSummarySeedInvalid = "legacy.high-school-summary.seed-invalid"
    case highSchoolSummaryChallengeStarted = "legacy.high-school-summary.challenge-started"
    case highSchoolSummaryFirstYear = "legacy.high-school-summary.first-year"
    case highSchoolSummaryRebirthMemories = "legacy.high-school-summary.rebirth.memories"
    case highSchoolSummaryRebirthSignature = "legacy.high-school-summary.rebirth.signature"
    case highSchoolSummaryRebirthBoth = "legacy.high-school-summary.rebirth.both"
    case highSchoolSummaryRebirthStarted = "legacy.high-school-summary.rebirth.started"
    case highSchoolSummaryRepeatTraining = "legacy.high-school-summary.repeat-training"
    case highSchoolSummaryProPending = "legacy.high-school-summary.pro-pending"
    case highSchoolSummaryGoalCompleted = "legacy.high-school-summary.goal-completed"
    case highSchoolSummaryNicknameEarned = "legacy.high-school-summary.nickname-earned"
    case highSchoolSummarySignatureLeft = "legacy.high-school-summary.signature-left"
    case highSchoolSummaryMemoriesLeft = "legacy.high-school-summary.memories-left"
    case highSchoolSummaryProMemoryChoice = "legacy.high-school-summary.pro-memory-choice"
    case highSchoolSummaryProLegacyFound = "legacy.high-school-summary.pro-legacy-found"
    case highSchoolSummaryPledgeChosen = "legacy.high-school-summary.pledge-chosen"
    case highSchoolSummaryCloudLoaded = "legacy.high-school-summary.cloud-loaded"
    case highSchoolSummaryCloudKeptLocal = "legacy.high-school-summary.cloud-kept-local"
    case highSchoolSummaryOutingAbandoned = "legacy.high-school-summary.outing-abandoned"
    case highSchoolSummaryChapterAdvanced = "legacy.high-school-summary.chapter-advanced"
    case highSchoolSummaryRelationship = "legacy.high-school-summary.relationship"
    case highSchoolSummaryRelationshipAbility = "legacy.high-school-summary.relationship.ability"
    case highSchoolSummaryAwakening = "legacy.high-school-summary.awakening"
    case highSchoolSummaryUpdated = "legacy.high-school-summary.updated"

    case heartCardTitle = "legacy.heart.card-title"
    case heartAccessibility = "legacy.heart.accessibility"
    case quoteHeading = "legacy.quote.heading"
    case quoteHeadingPlayer = "legacy.quote.heading.player"
    case quoteDefiningMoment = "legacy.quote.defining-moment"
    case quoteAccessibility = "legacy.quote.accessibility"
    case previousTitle = "legacy.previous.title"
    case previousRecipientSame = "legacy.previous.recipient.same"
    case previousRecipientNew = "legacy.previous.recipient.new"
    case previousMemories = "legacy.previous.memories"
    case previousSignature = "legacy.previous.signature"
    case previousAccessibility = "legacy.previous.accessibility"
    case bondMemoryHeading = "legacy.bond-memory.heading"
    case bondMemoryKindPersonality = "legacy.bond-memory.kind.personality"
    case bondMemoryKindHealth = "legacy.bond-memory.kind.health"
    case bondMemoryKindTrust = "legacy.bond-memory.kind.trust"
    case bondMemoryChoice = "legacy.bond-memory.choice"
    case bondMemoryTrust = "legacy.bond-memory.trust"
    case rebirthEchoSource = "legacy.rebirth-echo.source"

    case archiveTitle = "legacy.archive.title"
    case archiveStatDrafted = "legacy.archive.stat.drafted"
    case archiveStatStrikeouts = "legacy.archive.stat.strikeouts"
    case archiveStatEvaluation = "legacy.archive.stat.evaluation"
    case archiveStatPoints = "legacy.archive.stat.points"
    case archiveTotalsAccessibility = "legacy.archive.totals.accessibility"
    case archiveNextStrikeouts = "legacy.archive.next-strikeouts"
    case archiveBestStrikeouts = "legacy.archive.best-strikeouts"
    case archiveNicknameComplete = "legacy.archive.nickname.complete"
    case archiveNicknameIncomplete = "legacy.archive.nickname.incomplete"
    case archiveLineage = "legacy.archive.lineage"
    case archivePlayerNumber = "legacy.archive.player-number"
    case archivePlayerAccessibility = "legacy.archive.player.accessibility"
    case archiveDrafted = "legacy.archive.drafted"
    case archiveUndrafted = "legacy.archive.undrafted"
    case archiveOutcomeDrafted = "legacy.archive.outcome.drafted"
    case archiveOutcomeUndrafted = "legacy.archive.outcome.undrafted"
    case archiveCalledNames = "legacy.archive.called-names"
    case archiveRecordLine = "legacy.archive.record-line"
    case archiveSignature = "legacy.archive.signature"
    case archiveOtherSignatures = "legacy.archive.other-signatures"
    case archivePledgeStatusAchieved = "legacy.archive.pledge.status.achieved"
    case archivePledgeStatusClose = "legacy.archive.pledge.status.close"
    case archivePledgeStatusIncomplete = "legacy.archive.pledge.status.incomplete"
    case archivePledgeProgress = "legacy.archive.pledge.progress"
    case archivePledgeReward = "legacy.archive.pledge.reward"
    case archiveWind = "legacy.archive.wind"
    case archiveTalent = "legacy.archive.talent"
    case archiveAwakenings = "legacy.archive.awakenings"
    case archiveHandicaps = "legacy.archive.handicaps"
    case archiveSchoolStrength = "legacy.archive.school-strength"
    case archiveMemories = "legacy.archive.memories"
    case archiveShare = "legacy.archive.share"
    case archiveShareSubject = "legacy.archive.share.subject"
    case archiveTeamUnknown = "legacy.archive.team-unknown"
    case archiveEvaluation = "legacy.archive.evaluation"
    case archiveSummaryFooter = "legacy.archive.summary.footer"
    case archiveStatOutings = "legacy.archive.summary.stat.outings"
    case archiveStatWalks = "legacy.archive.summary.stat.walks"
    case archiveStatRuns = "legacy.archive.summary.stat.runs"

    case recapTitle = "legacy.recap.title"
    case recapStampDrafted = "legacy.recap.stamp.drafted"
    case recapStampUndrafted = "legacy.recap.stamp.undrafted"
    case recapStampRecord = "legacy.recap.stamp.record"
    case recapStampNickname = "legacy.recap.stamp.nickname"
    case recapGoalAchieved = "legacy.recap.goal.achieved"
    case recapGoalClose = "legacy.recap.goal.close"
    case recapGoalIncomplete = "legacy.recap.goal.incomplete"
    case recapRival = "legacy.recap.rival"
    case recapSignatureTitle = "legacy.recap.signature.title"
    case recapSignatureCandidates = "legacy.recap.signature.candidates"
    case recapPointsTitle = "legacy.recap.points.title"
    case recapPointsReceipt = "legacy.recap.points.receipt"
    case recapPointsSpend = "legacy.recap.points.spend"
    case recapPointsSave = "legacy.recap.points.save"
    case recapIntentTitle = "legacy.recap.intent.title"
    case recapIntentRetry = "legacy.recap.intent.retry"
    case recapIntentArchive = "legacy.recap.intent.archive"
    case recapIntentSave = "legacy.recap.intent.save"
    case recapIntentSaved = "legacy.recap.intent.saved"
    case recapIntentAccessibility = "legacy.recap.intent.accessibility"
    case recapQuickStart = "legacy.recap.quick-start"
    case recapContinue = "legacy.recap.continue"
    case recapCustomize = "legacy.recap.customize"
}

extension LegacyUICopyKey {
    var gameCopyKey: GameCopyKey { .localizable(rawValue) }
}

extension GameCopyResolver {
    func resolve(_ key: LegacyUICopyKey, arguments: [LocalizedCopyArgument] = []) -> String {
        resolve(key.gameCopyKey, arguments: arguments)
    }
}

extension AppCopyKey {
    static let legacyKeys = LegacyUICopyKey.allCases.map(\.gameCopyKey)
}
