import Foundation

/// Static iOS copy used by the direct-pitching surface.
///
/// The simulation continues to persist its legacy Korean diagnostic sentences. The pitching UI
/// resolves these semantic keys from structured pitch data instead of using those sentences as
/// lookup keys or English fallbacks.
enum PitchUICopyKey: String, CaseIterable, Sendable {
    case abort = "pitch.action.abort"
    case abortPracticeTitle = "pitch.abort.practice.title"
    case abortGameTitle = "pitch.abort.game.title"
    case abortPracticeConfirm = "pitch.abort.practice.confirm"
    case abortGameConfirm = "pitch.abort.game.confirm"
    case abortContinue = "pitch.abort.continue"
    case abortPracticeMessage = "pitch.abort.practice.message"
    case abortGameMessage = "pitch.abort.game.message"

    case coachLabel = "pitch.coach.label"
    case coachFirst = "pitch.coach.first"
    case coachSecond = "pitch.coach.second"
    case coachPutAway = "pitch.coach.put-away"
    case matchupTitle = "pitch.matchup.title"
    case matchupStats = "pitch.matchup.stats"
    case batterPractice = "pitch.batter.practice"
    case batterPracticeB = "pitch.batter.practice-b"
    case batterOpponent = "pitch.batter.opponent"
    case stateFailedTitle = "pitch.state.failed.title"
    case stateFailedBody = "pitch.state.failed.body"
    case statePlateEndedTitle = "pitch.state.plate-ended.title"
    case statePlateEndedBody = "pitch.state.plate-ended.body"

    case badgePerfectRelease = "pitch.badge.perfect-release"
    case badgeClutch = "pitch.badge.clutch"
    case badgeSequence = "pitch.badge.sequence"
    case traitActive = "pitch.trait.active"
    case traitCloserTitle = "pitch.trait.closer.title"
    case traitCloserBody = "pitch.trait.closer.body"
    case traitAnchorTitle = "pitch.trait.anchor.title"
    case traitAnchorBody = "pitch.trait.anchor.body"
    case traitTacticianTitle = "pitch.trait.tactician.title"
    case traitTacticianBody = "pitch.trait.tactician.body"
    case traitOpenerTitle = "pitch.trait.opener.title"
    case traitOpenerBody = "pitch.trait.opener.body"

    case zoneHighInside = "pitch.zone.high-inside"
    case zoneHighMiddle = "pitch.zone.high-middle"
    case zoneHighOutside = "pitch.zone.high-outside"
    case zoneMiddleInside = "pitch.zone.middle-inside"
    case zoneMiddleMiddle = "pitch.zone.middle-middle"
    case zoneMiddleOutside = "pitch.zone.middle-outside"
    case zoneLowInside = "pitch.zone.low-inside"
    case zoneLowMiddle = "pitch.zone.low-middle"
    case zoneLowOutside = "pitch.zone.low-outside"
    case zoneUnknown = "pitch.zone.unknown"
    case zoneIn = "pitch.zone.in"
    case zoneOut = "pitch.zone.out"
    case zoneIntentStrikeDetail = "pitch.intent.strike.detail"
    case zoneIntentEdgeDetail = "pitch.intent.edge.detail"
    case zoneIntentChaseMiddleDetail = "pitch.intent.chase.middle.detail"
    case zoneIntentChaseDetail = "pitch.intent.chase.detail"

    case feedbackSelectionPoor = "pitch.feedback.selection.poor"
    case feedbackSelectionRisky = "pitch.feedback.selection.risky"
    case feedbackSelectionGood = "pitch.feedback.selection.good"
    case feedbackSelectionExcellent = "pitch.feedback.selection.excellent"
    case feedbackDetail = "pitch.feedback.detail"
    case feedbackBall = "pitch.feedback.outcome.ball"
    case feedbackCalledStrike = "pitch.feedback.outcome.called-strike"
    case feedbackSwingingStrike = "pitch.feedback.outcome.swinging-strike"
    case feedbackFoul = "pitch.feedback.outcome.foul"
    case feedbackInPlayOut = "pitch.feedback.outcome.in-play-out"
    case feedbackSingle = "pitch.feedback.outcome.single"
    case feedbackDouble = "pitch.feedback.outcome.double"
    case feedbackTriple = "pitch.feedback.outcome.triple"
    case feedbackHomeRun = "pitch.feedback.outcome.home-run"
    case feedbackHitByPitch = "pitch.feedback.outcome.hit-by-pitch"

    case abilityPowerMoment = "pitch.ability.power.moment"
    case abilityCommandMoment = "pitch.ability.command.moment"
    case abilityMovementMoment = "pitch.ability.movement.moment"
    case abilityStaminaMoment = "pitch.ability.stamina.moment"
    case abilitySummary = "pitch.ability.accessibility-summary"
    case buildPowerPrimary = "pitch.build.power.primary"
    case buildPowerSecondary = "pitch.build.power.secondary"
    case buildCommand = "pitch.build.command"
    case buildMovementPrimary = "pitch.build.movement.primary"
    case buildMovementSecondary = "pitch.build.movement.secondary"
    case buildStamina = "pitch.build.stamina"

    case sequenceSpeedLadderTitle = "pitch.sequence.speed-ladder.title"
    case sequenceSpeedLadderDetail = "pitch.sequence.speed-ladder.detail"
    case sequenceEyeLevelTitle = "pitch.sequence.eye-level.title"
    case sequenceEyeLevelDetail = "pitch.sequence.eye-level.detail"
    case sequenceInsideOutsideTitle = "pitch.sequence.inside-outside.title"
    case sequenceInsideOutsideDetail = "pitch.sequence.inside-outside.detail"
    case sequenceExpandTitle = "pitch.sequence.expand.title"
    case sequenceExpandDetail = "pitch.sequence.expand.detail"
    case sequenceStealStrikeTitle = "pitch.sequence.steal-strike.title"
    case sequenceStealStrikeDetail = "pitch.sequence.steal-strike.detail"
    case sequenceCounterReadTitle = "pitch.sequence.counter-read.title"
    case sequenceCounterReadDetail = "pitch.sequence.counter-read.detail"

    case practiceReadyTitle = "pitch.practice.ready.title"
    case practiceLesson = "pitch.practice.lesson"
    case practiceNotRecorded = "pitch.practice.not-recorded"
    case practiceRetry = "pitch.practice.retry"
    case inningEndTitle = "pitch.inning.end.title"
    case inningLine = "pitch.inning.line"
    case inningLineWithHBP = "pitch.inning.line.hbp"
    case inningProcessGood = "pitch.inning.process.good"
    case inningProcessReview = "pitch.inning.process.review"
    case pitchLogTitle = "pitch.log.title"

    case selectionPitchTitle = "pitch.selection.pitch.title"
    case selectionZoneTitle = "pitch.selection.zone.title"
    case selectionPlanTitle = "pitch.selection.plan.title"
    case autoRelease = "pitch.auto-release.label"
    case fastForwardTitle = "pitch.fast-forward.title"
    case fastForwardBody = "pitch.fast-forward.body"
    case nextBatter = "pitch.action.next-batter"
    case startCareer = "pitch.action.start-career"
    case finishOuting = "pitch.action.finish-outing"
    case statWhiffs = "pitch.stat.whiffs"
    case statStrikeouts = "pitch.stat.strikeouts"
    case statTopVelocity = "pitch.stat.top-velocity"
    case statWhiffRecord = "pitch.stat.whiff-record"
    case statReleaseTitle = "pitch.stat.release-title"
    case statPersonalBest = "pitch.stat.personal-best"
    case statReleaseBest = "pitch.stat.release-best"
    case statReleaseCompare = "pitch.stat.release-compare"

    case scoreboardTied = "pitch.scoreboard.tied"
    case scoreboardAhead = "pitch.scoreboard.ahead"
    case scoreboardBehind = "pitch.scoreboard.behind"
    case scoreboardFatigue = "pitch.scoreboard.fatigue"
    case scoreboardLine = "pitch.scoreboard.line"
    case scoreboardLineWithHBP = "pitch.scoreboard.line.hbp"
    case scoreboardAccessibility = "pitch.scoreboard.accessibility"
    case scoreboardOuting = "pitch.scoreboard.accessibility.outing"
    case runnersNone = "pitch.runners.none"
    case runnersLoaded = "pitch.runners.loaded"
    case runnersOccupied = "pitch.runners.occupied"
    case runnersAccessibility = "pitch.runners.accessibility"
    case stakesLabel = "pitch.stakes.label"
    case stakesRoutine = "pitch.stakes.routine"
    case stakesSwing = "pitch.stakes.swing"
    case stakesHigh = "pitch.stakes.high"
    case stakesMaximum = "pitch.stakes.maximum"
    case stakesAccessibility = "pitch.stakes.accessibility"

    case buildCardTitle = "pitch.build.card.title"
    case buildCompact = "pitch.build.compact"
    case buildVelocity = "pitch.build.metric.velocity"
    case buildCommandMetric = "pitch.build.metric.command"
    case buildMovementMetric = "pitch.build.metric.movement"
    case buildStaminaMetric = "pitch.build.metric.stamina"
    case buildFatigueCost = "pitch.build.fatigue-cost"
    case adaptationTitle = "pitch.adaptation.title"
    case adaptationNoData = "pitch.adaptation.no-data"
    case adaptationWatching = "pitch.adaptation.watching"
    case adaptationLearning = "pitch.adaptation.learning"
    case adaptationLocked = "pitch.adaptation.locked"
    case adaptationQuiet = "pitch.adaptation.quiet"
    case adaptationPitch = "pitch.adaptation.pitch"
    case adaptationZone = "pitch.adaptation.zone"
    case adaptationPitchAndZone = "pitch.adaptation.pitch-and-zone"
    case adaptationAccessibility = "pitch.adaptation.accessibility"

    case analysisTitle = "pitch.analysis.title"
    case analysisLow = "pitch.analysis.confidence.low"
    case analysisDeveloping = "pitch.analysis.confidence.developing"
    case analysisReliable = "pitch.analysis.confidence.reliable"
    case analysisSample = "pitch.analysis.sample"
    case analysisZoneRate = "pitch.analysis.zone-rate"
    case analysisWhiffRate = "pitch.analysis.whiff-rate"
    case analysisHardHitRate = "pitch.analysis.hard-hit-rate"
    case analysisCommand = "pitch.analysis.command"
    case analysisExpectedDamage = "pitch.analysis.expected-damage"
    case analysisActualDamage = "pitch.analysis.actual-damage"
    case analysisPatternWarning = "pitch.analysis.pattern-warning"
    case analysisGrowthSignal = "pitch.analysis.growth-signal"
    case analysisBreakdownSmall = "pitch.analysis.breakdown.small"
    case analysisBreakdown = "pitch.analysis.breakdown"

    case catcherSynced = "pitch.catcher.card.synced"
    case catcherMatches = "pitch.catcher.card.matches"
    case catcherManual = "pitch.catcher.card.manual"
    case catcherSelected = "pitch.catcher.selected"
    case catcherConfidence = "pitch.catcher.confidence"
    case catcherProposal = "pitch.catcher.proposal"
    case catcherPrimary = "pitch.catcher.primary"
    case catcherAlternative = "pitch.catcher.alternative"
    case catcherRiskWalk = "pitch.catcher.risk.walk"
    case catcherRiskDamage = "pitch.catcher.risk.damage"
    case catcherRiskMiss = "pitch.catcher.risk.miss"
    case catcherHold = "pitch.catcher.hold"
    case catcherHoldBody = "pitch.catcher.hold.body"
    case catcherScout = "pitch.catcher.scout"
    case catcherScoutTrusted = "pitch.catcher.scout.trusted"
    case catcherScoutEstimate = "pitch.catcher.scout.estimate"
    case catcherScoutAvoid = "pitch.catcher.scout.avoid"
    case catcherAccept = "pitch.catcher.accept"
    case catcherBondOneBreath = "pitch.catcher.bond.one-breath"
    case catcherBondAligned = "pitch.catcher.bond.aligned"
    case catcherBondLearning = "pitch.catcher.bond.learning"
    case catcherBondCrossed = "pitch.catcher.bond.crossed"
    case catcherReasonPattern = "pitch.catcher.reason.pattern"
    case catcherReasonRepeat = "pitch.catcher.reason.repeat"
    case catcherReasonWeakness = "pitch.catcher.reason.weakness"
    case catcherReasonWalk = "pitch.catcher.reason.walk"
    case catcherReasonBehind = "pitch.catcher.reason.behind"
    case catcherReasonAhead = "pitch.catcher.reason.ahead"
    case catcherReasonFirstPitch = "pitch.catcher.reason.first-pitch"
    case catcherReasonDoublePlay = "pitch.catcher.reason.double-play"
    case catcherReasonSacFly = "pitch.catcher.reason.sac-fly"
    case catcherReasonDefault = "pitch.catcher.reason.default"

    case zoneRecommended = "pitch.zone-grid.recommended"
    case zoneHot = "pitch.zone-grid.hot"
    case zoneCold = "pitch.zone-grid.cold"
    case zoneLegendAccessibility = "pitch.zone-grid.legend.accessibility"
    case zoneCellRecommended = "pitch.zone-grid.cell.recommended"
    case zoneCellHot = "pitch.zone-grid.cell.hot"
    case zoneCellCold = "pitch.zone-grid.cell.cold"
    case zoneMiniIn = "pitch.zone-mini.in"
    case zoneMiniOut = "pitch.zone-mini.out"
    case strikeoutAccessibility = "pitch.strikeout.accessibility"

    case settlementTitle = "pitch.settlement.title"
    case settlementStrikeouts = "pitch.settlement.strikeouts"
    case settlementScoreless = "pitch.settlement.scoreless"
    case settlementSpark = "pitch.settlement.spark"
    case settlementStrikeoutStreak = "pitch.settlement.strikeout-streak"
    case settlementSequence = "pitch.settlement.sequence"
    case settlementNextLesson = "pitch.settlement.next-lesson"

    case deliveryTempoFast = "pitch.delivery.tempo.fast"
    case deliveryTempoNormal = "pitch.delivery.tempo.normal"
    case deliveryTempoSlow = "pitch.delivery.tempo.slow"
    case deliveryThrow = "pitch.delivery.throw"
    case deliveryAutoHint = "pitch.delivery.auto.hint"
    case deliveryTitle = "pitch.delivery.title"
    case deliveryNowPerfect = "pitch.delivery.now.perfect"
    case deliveryNow = "pitch.delivery.now"
    case deliveryWait = "pitch.delivery.wait"
    case deliveryAim = "pitch.delivery.aim"
    case deliveryHold = "pitch.delivery.hold"
    case deliveryHoldLonger = "pitch.delivery.hold-longer"
    case deliveryAccessibilityLabel = "pitch.delivery.accessibility.label"
    case deliveryAccessibilityHint = "pitch.delivery.accessibility.hint"
    case deliveryVerdictPerfect = "pitch.delivery.verdict.perfect"
    case deliveryVerdictExcellent = "pitch.delivery.verdict.excellent"
    case deliveryVerdictGood = "pitch.delivery.verdict.good"
    case deliveryVerdictOkay = "pitch.delivery.verdict.okay"
    case deliveryVerdictMissed = "pitch.delivery.verdict.missed"
    case deliveryHintReleaseLarge = "pitch.delivery.hint.release.large"
    case deliveryHintReleaseSmall = "pitch.delivery.hint.release.small"
    case deliveryHintAimLarge = "pitch.delivery.hint.aim.large"
    case deliveryHintAimSmall = "pitch.delivery.hint.aim.small"

    case dramaAccessibility = "pitch.drama.accessibility"
    case dramaFielding = "pitch.drama.fielding"
    case dramaSequence = "pitch.drama.sequence"
    case fielderPitcher = "pitch.fielder.pitcher"
    case fielderCatcher = "pitch.fielder.catcher"
    case fielderFirstBase = "pitch.fielder.first-base"
    case fielderSecondBase = "pitch.fielder.second-base"
    case fielderThirdBase = "pitch.fielder.third-base"
    case fielderShortstop = "pitch.fielder.shortstop"
    case fielderLeftField = "pitch.fielder.left-field"
    case fielderCenterField = "pitch.fielder.center-field"
    case fielderRightField = "pitch.fielder.right-field"

    case scenarioProDebutTitle = "pitch.scenario.pro.debut.title"
    case scenarioProDebutBody = "pitch.scenario.pro.debut.body"
    case scenarioProCallUpTitle = "pitch.scenario.pro.call-up.title"
    case scenarioProCallUpBody = "pitch.scenario.pro.call-up.body"
    case scenarioProRoleTitle = "pitch.scenario.pro.role.title"
    case scenarioProRoleBody = "pitch.scenario.pro.role.body"
    case scenarioProRecordTitle = "pitch.scenario.pro.record.title"
    case scenarioProRecordAheadBody = "pitch.scenario.pro.record.ahead.body"
    case scenarioProRecordBehindBody = "pitch.scenario.pro.record.behind.body"
    case scenarioProStandingsTitle = "pitch.scenario.pro.standings.title"
    case scenarioProStandingsAheadBody = "pitch.scenario.pro.standings.ahead.body"
    case scenarioProStandingsBehindBody = "pitch.scenario.pro.standings.behind.body"
    case scenarioProOpeningTitle = "pitch.scenario.pro.opening.title"
    case scenarioProOpeningBody = "pitch.scenario.pro.opening.body"
    case scenarioTutorialTitle = "pitch.scenario.tutorial.title"
    case scenarioTutorialBody = "pitch.scenario.tutorial.body"
}

extension PitchUICopyKey {
    var gameCopyKey: GameCopyKey { .localizable(rawValue) }
}

extension GameCopyResolver {
    func resolve(_ key: PitchUICopyKey, arguments: [LocalizedCopyArgument] = []) -> String {
        resolve(key.gameCopyKey, arguments: arguments)
    }
}

extension AppCopyKey {
    static let pitchKeys = PitchUICopyKey.allCases.map(\.gameCopyKey)
}
