import Foundation

/// Static copy for the professional-career, league, and record surfaces.
///
/// Stored professional snapshots intentionally keep their shipped Korean diagnostic sentences.
/// English UI resolves these semantic keys from stable IDs and typed values instead of displaying
/// a stored sentence or using it as a lookup key.
enum ProUICopyKey: String, CaseIterable, Sendable {
    case navigationThisWeek = "pro.flow.navigation.this-week"
    case seasonDecisionUnavailable = "pro.flow.unavailable.season-decision"
    case scheduleComplete = "pro.flow.unavailable.schedule-complete"
    case seasonReviewTitle = "pro.flow.season-review.title"
    case seasonReviewBody = "pro.flow.season-review.body"
    case seasonReviewAction = "pro.flow.season-review.action"

    case summaryPlayer = "pro.summary.player"
    case summaryName = "pro.summary.name"
    case summaryTeam = "pro.summary.team"
    case summaryLevel = "pro.summary.level"
    case summaryRole = "pro.summary.role"
    case summaryAbility = "pro.summary.ability"
    case summaryStuff = "pro.summary.stuff"
    case summaryCommand = "pro.summary.command"
    case summaryMovement = "pro.summary.movement"
    case summaryStamina = "pro.summary.stamina"
    case summaryMilestones = "pro.summary.milestones"
    case summaryDecisions = "pro.summary.decisions"
    case summaryDecisionLine = "pro.summary.decision-line"
    case summaryNavigation = "pro.summary.navigation"

    case decisionEyebrow = "pro.decision.eyebrow"
    case decisionAccessibility = "pro.decision.choice.accessibility"
    case decisionHint = "pro.decision.choice.hint"
    case decisionWarning = "pro.decision.warning"
    case decisionConfirmTitle = "pro.decision.confirm.title"
    case decisionConfirmAction = "pro.decision.confirm.action"
    case decisionConfirmCancel = "pro.decision.confirm.cancel"
    case decisionConfirmMessage = "pro.decision.confirm.message"
    case effectStuffGain = "pro.effect.stuff.gain"
    case effectStuffLoss = "pro.effect.stuff.loss"
    case effectCommandGain = "pro.effect.command.gain"
    case effectCommandLoss = "pro.effect.command.loss"
    case effectMovementGain = "pro.effect.movement.gain"
    case effectMovementLoss = "pro.effect.movement.loss"
    case effectStaminaGain = "pro.effect.stamina.gain"
    case effectStaminaLoss = "pro.effect.stamina.loss"
    case effectManagerGain = "pro.effect.manager-trust.gain"
    case effectManagerLoss = "pro.effect.manager-trust.loss"
    case effectCatcherGain = "pro.effect.catcher-trust.gain"
    case effectCatcherLoss = "pro.effect.catcher-trust.loss"
    case effectFatigueGain = "pro.effect.fatigue.gain"
    case effectFatigueLoss = "pro.effect.fatigue.loss"
    case effectRole = "pro.effect.role"

    case weeklyFatigue = "pro.weekly.metric.fatigue"
    case weeklyManagerTrust = "pro.weekly.metric.manager-trust"
    case weeklyRole = "pro.weekly.metric.role"
    case weeklyBlueprint = "pro.weekly.blueprint"
    case weeklyRolePromise = "pro.weekly.role-promise"
    case weeklyTitle = "pro.weekly.title"
    case weeklyRoutine = "pro.weekly.routine"
    case weeklyArcRookie = "pro.weekly.arc.rookie"
    case weeklyArcPrime = "pro.weekly.arc.prime"
    case weeklyArcVeteran = "pro.weekly.arc.veteran"
    case weeklyProgress = "pro.weekly.progress"
    case weeklyDevelopStuffRelief = "pro.weekly.plan.stuff.relief.title"
    case weeklyDevelopStuffVeteran = "pro.weekly.plan.stuff.veteran.title"
    case weeklyDevelopStuffStarter = "pro.weekly.plan.stuff.starter.title"
    case weeklyDevelopStuffEffect = "pro.weekly.plan.stuff.effect"
    case weeklyDevelopStuffCost = "pro.weekly.plan.stuff.cost"
    case weeklyDevelopMovementTitle = "pro.weekly.plan.movement.title"
    case weeklyDevelopMovementEffect = "pro.weekly.plan.movement.effect"
    case weeklyDevelopMovementCost = "pro.weekly.plan.movement.cost"
    case weeklyCommandTitle = "pro.weekly.plan.command.title"
    case weeklyCommandEffect = "pro.weekly.plan.command.effect"
    case weeklyCommandCost = "pro.weekly.plan.command.cost"
    case weeklyStaminaReliefTitle = "pro.weekly.plan.stamina.relief.title"
    case weeklyStaminaStarterTitle = "pro.weekly.plan.stamina.starter.title"
    case weeklyStaminaEffect = "pro.weekly.plan.stamina.effect"
    case weeklyStaminaCost = "pro.weekly.plan.stamina.cost"
    case weeklyRecoveryVeteranTitle = "pro.weekly.plan.recovery.veteran.title"
    case weeklyRecoveryTitle = "pro.weekly.plan.recovery.title"
    case weeklyRecoveryEffect = "pro.weekly.plan.recovery.effect"
    case weeklyRecoveryCost = "pro.weekly.plan.recovery.cost"
    case weeklyTrustMinorTitle = "pro.weekly.plan.trust.minor.title"
    case weeklyTrustReliefTitle = "pro.weekly.plan.trust.relief.title"
    case weeklyTrustStarterTitle = "pro.weekly.plan.trust.starter.title"
    case weeklyTrustEffect = "pro.weekly.plan.trust.effect"
    case weeklyTrustCost = "pro.weekly.plan.trust.cost"
    case weeklyRecommendInjury = "pro.weekly.recommendation.injury"
    case weeklyRecommendCallUp = "pro.weekly.recommendation.call-up"
    case weeklyRecommendPower = "pro.weekly.recommendation.power"
    case weeklyRecommendCommand = "pro.weekly.recommendation.command"
    case weeklyRecommendMovement = "pro.weekly.recommendation.movement"
    case weeklyRecommendStamina = "pro.weekly.recommendation.stamina"
    case weeklyDevelopmentPitch = "pro.weekly.development-pitch"
    case weeklyAdvance = "pro.weekly.advance"
    case weeklyAdvanceSegment = "pro.weekly.advance-segment"
    case weeklyAdvanceStop = "pro.weekly.advance-stop"

    case importantEyebrow = "pro.important.eyebrow"
    case importantMajorTitle = "pro.important.major.title"
    case importantMinorOpportunityTitle = "pro.important.minor.opportunity.title"
    case importantMinorRoleTitle = "pro.important.minor.role.title"
    case importantOpponent = "pro.important.opponent"
    case importantMyStatus = "pro.important.my-status"
    case importantFatigue = "pro.important.fatigue"
    case importantManagerTrust = "pro.important.manager-trust"
    case importantCatcherTrust = "pro.important.catcher-trust"
    case importantBody = "pro.important.body"
    case importantAction = "pro.important.action"

    case offseasonEyebrow = "pro.offseason.eyebrow"
    case offseasonTitle = "pro.offseason.title"
    case offseasonService = "pro.offseason.service"
    case offseasonMilitary = "pro.offseason.military"
    case offseasonCareer = "pro.offseason.career"
    case offseasonYears = "pro.offseason.years"
    case offseasonSeasons = "pro.offseason.seasons"
    case offseasonMilitaryComplete = "pro.offseason.military.complete"
    case offseasonMilitaryIncomplete = "pro.offseason.military.incomplete"
    case offseasonContinueDetail = "pro.offseason.continue.detail"
    case offseasonMilitaryDetail = "pro.offseason.military.detail"
    case offseasonMilitaryDone = "pro.offseason.military.done"
    case offseasonFreeAgencyDetail = "pro.offseason.free-agency.detail"
    case offseasonFreeAgencyLocked = "pro.offseason.free-agency.locked"
    case offseasonRetireDetail = "pro.offseason.retire.detail"
    case offseasonIrreversible = "pro.offseason.irreversible"
    case offseasonConfirmRetireTitle = "pro.offseason.confirm.retire.title"
    case offseasonConfirmMilitaryTitle = "pro.offseason.confirm.military.title"
    case offseasonConfirmFreeAgencyTitle = "pro.offseason.confirm.free-agency.title"
    case offseasonConfirmContinueTitle = "pro.offseason.confirm.continue.title"
    case offseasonConfirmRetireAction = "pro.offseason.confirm.retire.action"
    case offseasonConfirmMilitaryAction = "pro.offseason.confirm.military.action"
    case offseasonConfirmFreeAgencyAction = "pro.offseason.confirm.free-agency.action"
    case offseasonConfirmContinueAction = "pro.offseason.confirm.continue.action"
    case offseasonConfirmCancel = "pro.offseason.confirm.cancel"
    case offseasonConfirmRetireMessage = "pro.offseason.confirm.retire.message"
    case offseasonConfirmMilitaryMessage = "pro.offseason.confirm.military.message"
    case offseasonConfirmFreeAgencyMessage = "pro.offseason.confirm.free-agency.message"
    case offseasonConfirmContinueMessage = "pro.offseason.confirm.continue.message"

    case retirementEyebrow = "pro.retirement.eyebrow"
    case retirementDecisionTitle = "pro.retirement.decision.title"
    case retirementHere = "pro.retirement.here"
    case retirementDecisionBody = "pro.retirement.decision.body"
    case retirementAction = "pro.retirement.action"
    case retirementConfirmTitle = "pro.retirement.confirm.title"
    case retirementConfirmAction = "pro.retirement.confirm.action"
    case retirementConfirmCancel = "pro.retirement.confirm.cancel"
    case retirementConfirmMessage = "pro.retirement.confirm.message"
    case retiredEyebrow = "pro.retired.eyebrow"
    case retiredTitle = "pro.retired.title"
    case retiredIdentityLine = "pro.retired.identity-line"
    case retiredHallOfFame = "pro.retired.hall-of-fame"
    case retiredLegacyTitle = "pro.retired.legacy.title"
    case retiredSoulTitle = "pro.retired.soul.title"
    case retiredLegacyBody = "pro.retired.legacy.body"
    case retiredSoulBody = "pro.retired.soul.body"
    case retiredSoulPoints = "pro.retired.soul-points"
    case retiredAwards = "pro.retired.awards"
    case retiredRetrospective = "pro.retired.retrospective"
    case retiredLegacyAction = "pro.retired.legacy.action"
    case retiredSoulAction = "pro.retired.soul.action"
    case retiredLegacyFootnote = "pro.retired.legacy.footnote"
    case retiredSoulFootnote = "pro.retired.soul.footnote"
    case retiredLegacyConfirmTitle = "pro.retired.legacy.confirm.title"
    case retiredSoulConfirmTitle = "pro.retired.soul.confirm.title"
    case retiredLegacyConfirmAction = "pro.retired.legacy.confirm.action"
    case retiredSoulConfirmAction = "pro.retired.soul.confirm.action"
    case retiredConfirmCancel = "pro.retired.confirm.cancel"
    case retiredLegacyConfirmMessage = "pro.retired.legacy.confirm.message"
    case retiredSoulConfirmMessage = "pro.retired.soul.confirm.message"

    case totalsTitle = "pro.totals.title"
    case totalsGames = "pro.totals.games"
    case totalsInnings = "pro.totals.innings"
    case totalsStrikeouts = "pro.totals.strikeouts"
    case totalsRecord = "pro.totals.record"
    case totalsRA9 = "pro.totals.ra9"
    case totalsSeasons = "pro.totals.seasons"

    case leagueInnings = "league.metric.innings"
    case leagueRA9 = "league.metric.ra9"
    case leagueStrikeoutRate = "league.metric.strikeout-rate"
    case leagueQualityStarts = "league.metric.quality-starts"
    case leagueSmallSample = "league.interpretation.small-sample"
    case leagueFIPHigher = "league.interpretation.fip-lower"
    case leagueFIPLower = "league.interpretation.fip-higher"
    case leagueFIPAligned = "league.interpretation.aligned"
    case leagueMethodNote = "league.method-note"
    case leagueStandingsTitle = "league.standings.title"
    case leagueTeam = "league.standings.team"
    case leagueHeader = "league.standings.header"
    case leagueStandingAccessibility = "league.standings.accessibility"
    case leaguePitchersTitle = "league.pitchers.title"
    case leagueSort = "league.pitchers.sort"
    case leagueSortRA9 = "league.pitchers.sort.ra9"
    case leagueSortWHIP = "league.pitchers.sort.whip"
    case leagueSortStrikeouts = "league.pitchers.sort.strikeouts"
    case leagueSortWins = "league.pitchers.sort.wins"
    case leagueInningsValue = "league.pitchers.innings-value"
    case leaguePitcherAccessibility = "league.pitchers.accessibility"
    case leagueWinLoss = "league.pitchers.win-loss"
}

extension ProUICopyKey {
    var gameCopyKey: GameCopyKey { .localizable(rawValue) }
}

extension GameCopyResolver {
    func resolve(_ key: ProUICopyKey, arguments: [LocalizedCopyArgument] = []) -> String {
        resolve(key.gameCopyKey, arguments: arguments)
    }
}

extension AppCopyKey {
    static let proFlowKeys = ProUICopyKey.allCases.map(\.gameCopyKey)
}
