import Foundation

/// 전국 고교 유망주 랭킹 — 드래프트라는 최종 시험 전에 세상이 매기는 중간 점수.
///
/// 순위표는 프로에만 있었고, 고교 3년 동안 "전국에서 내가 몇 번째인가"를 답해 주는
/// 화면이 없었다. 그 답이 매 경기 갱신될 때 드래프트 기대감이 매주의 감정이 된다.
///
/// 결정론: 경쟁 유망주 명단은 careerID 시드로, 내 순위는 누적 성적의 순수 함수로
/// 정해진다. 커널 난수 경로와 분리돼 있어 골든 픽스처에 영향이 없다.
public enum ProspectRanking {
    public struct Entry: Equatable, Sendable, Identifiable {
        public let rank: Int
        public let name: String
        public let school: String
        /// 스카우트 한 줄 평 — 이 선수가 왜 여기 있는가.
        public let tag: String
        public let isPlayer: Bool
        /// Ephemeral identity for localized presentation. The legacy Korean fields above remain
        /// the public raw board contract and are generated by the same deterministic path.
        public let presentationIdentity: PresentationIdentity?

        public init(
            rank: Int,
            name: String,
            school: String,
            tag: String,
            isPlayer: Bool,
            presentationIdentity: PresentationIdentity? = nil
        ) {
            self.rank = rank
            self.name = name
            self.school = school
            self.tag = tag
            self.isPlayer = isPlayer
            self.presentationIdentity = presentationIdentity
        }

        public var id: Int { rank }
    }

    /// 랭킹은 20위까지만 발표된다. 그 밖은 "랭킹 밖" — 진입 자체가 첫 사건이 되도록.
    public static let boardSize = 20

    /// 내 전국 순위. 아직 등판이 없으면 nil(세상이 모른다), 성적이 모자라면
    /// boardSize 밖의 순위가 나온다 — 그것도 "몇 계단 남았는지"를 말해 주는 정보다.
    public static func playerRank(performance: CareerPerformanceSnapshot) -> Int? {
        let games = performance.importantGamesCompleted
        guard games > 0 else { return nil }
        // 평가 점수: 탈삼진은 재능, 볼넷·실점은 감점, 경기 수는 검증된 표본.
        let score = performance.strikeouts * 3 - performance.walks * 2
            - performance.runsAllowed * 3 + games * 4
        // 점수 0 이하 = 60위권(무명), 점수가 쌓일수록 계단을 오른다. 1위는 90점 —
        // 5경기 30탈삼진 무실점급이 도달하는 자리다.
        let rank = max(1, 60 - (score * 59) / 90)
        return rank
    }

    /// 발표된 랭킹 보드. 내가 20위 안이면 명단에 함께 실린다.
    public static func board(careerID: String, playerName: String, playerSchool: String,
                             performance: CareerPerformanceSnapshot) -> [Entry] {
        var generator = SplitMix64(seed: StableHash.fnv1a64Value("prospect|\(careerID)"))
        let surnames = ProspectRankingPresentationCatalog.surnameDescriptors
        let given = ProspectRankingPresentationCatalog.givenNameDescriptors
        let schools = ProspectRankingPresentationCatalog.schoolDescriptors
        let tags = ProspectRankingPresentationCatalog.scoutTagDescriptors

        // 명단은 회차마다 다르되 그 회차 안에서는 고정 — 라이벌은 얼굴이 있어야 한다.
        var names: Set<String> = [playerName]
        var rivals: [(String, String, String, PresentationIdentity)] = []
        while rivals.count < Self.boardSize {
            let surnameIndex = generator.nextInt(upperBound: surnames.count)
            let givenIndex = generator.nextInt(upperBound: given.count)
            let surname = surnames[surnameIndex]
            let givenName = given[givenIndex]
            let name = surname.koreanValue + givenName.koreanValue
            guard !names.contains(name) else { continue }
            let schoolIndex = generator.nextInt(upperBound: schools.count)
            let tagIndex = generator.nextInt(upperBound: tags.count)
            names.insert(name)
            rivals.append((
                name,
                schools[schoolIndex].rawSchoolName,
                tags[tagIndex].koreanValue,
                .rival(
                    surnameID: ProspectSurnameComponentID.allCases[surnameIndex],
                    givenNameID: ProspectGivenNameComponentID.allCases[givenIndex],
                    schoolID: schools[schoolIndex].id,
                    scoutTagID: tags[tagIndex].id
                )
            ))
        }

        let mine = playerRank(performance: performance)
        var entries: [Entry] = []
        var rivalIndex = 0
        for rank in 1...Self.boardSize {
            if rank == mine {
                entries.append(Entry(rank: rank, name: playerName, school: playerSchool,
                                     tag: "이 명단에서 유일하게 당신이 키우는 선수", isPlayer: true,
                                     presentationIdentity: .player()))
            } else {
                let rival = rivals[rivalIndex]
                rivalIndex += 1
                entries.append(Entry(rank: rank, name: rival.0, school: rival.1, tag: rival.2,
                                     isPlayer: false, presentationIdentity: rival.3))
            }
        }
        return entries
    }

    /// The iOS presentation path adds the selected-school identity to the player row after the
    /// exact same board has been generated. No random draw, raw entry, or rank changes here.
    public static func presentationBoard(
        careerID: String,
        playerName: String,
        playerSchool: String,
        playerSchoolID: SchoolID?,
        playerRegion: SchoolRegionID?,
        performance: CareerPerformanceSnapshot
    ) -> [Entry] {
        board(
            careerID: careerID,
            playerName: playerName,
            playerSchool: playerSchool,
            performance: performance
        ).map { entry in
            guard entry.isPlayer else { return entry }
            return Entry(
                rank: entry.rank,
                name: entry.name,
                school: entry.school,
                tag: entry.tag,
                isPlayer: true,
                presentationIdentity: .player(schoolID: playerSchoolID, region: playerRegion)
            )
        }
    }
}
