import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — Mound Reborn",
  description:
    "How Mound Reborn handles game progress, product analytics, diagnostics, and platform services on iOS and Android.",
  alternates: {
    canonical: "/en/privacy",
    languages: { "ko-KR": "/privacy", "en-US": "/en/privacy" },
  },
};

const lastUpdated = "August 13, 2026";

const sections = [
  {
    title: "Scope",
    paragraphs: [
      "This policy applies to the iOS and Android editions of Mound Reborn (야구 못하면 또 환생함). Platform features differ, so the information handled by each edition is described below.",
      "The game does not require an account or request your name, email address, phone number, contacts, photos, microphone, or precise location. It contains no advertising, does not use an advertising identifier, and does not track you for behavioral advertising.",
    ],
  },
  {
    title: "Game data stored on your device",
    paragraphs: [
      "Career progress—including player attributes, game records, completed lives, and achievements—along with player names and seeds you enter and settings such as sound, haptics, and notifications, is stored primarily on your device.",
      "We do not send player names, original seeds, career identifiers, save-file contents, free-form text, or shared images to analytics or crash-diagnostic services.",
      "You can remove local game data and replace the app-generated pseudonymous installation identifier by using the in-app reset option or deleting the app, subject to any synchronized platform copy described below.",
    ],
  },
  {
    title: "Apple services used on iOS",
    paragraphs: [
      "Career progress may be stored in Apple's iCloud key-value storage so you can continue on another device using the same Apple Account. This data belongs to your iCloud account, is not directly accessible to us, and can be disabled in your device's iCloud settings.",
      "The iOS app uses Apple Game Center for achievements and leaderboards. Apple operates this service, and the display of nicknames and scores follows Apple's policies.",
      "You can play without signing in to Game Center. Earned progress remains available in the game on your device.",
    ],
  },
  {
    title: "Product analytics and diagnostics",
    paragraphs: [
      "The iOS and Android editions use Firebase Analytics and Amplitude to process product interactions such as screens, career stages, and feature use, together with app version, build, operating-system information, and performance information. A pseudonymous identifier generated by the app and identifiers generated by those services may also be processed.",
      "Firebase Analytics may use the IP address involved in transmission to derive an approximate country- or city-level location. The game does not request location permission or collect GPS, Wi-Fi, or other precise location data.",
      "Firebase Crashlytics on Android and diagnostic services supplied by the platforms may process crash logs, stack traces, app, operating-system, and device state, crash-session information, and installation identifiers to diagnose errors and improve stability. We do not set an account identifier or advertising identifier as a diagnostics user ID.",
      "We use this information only for product analytics, error diagnosis, and service reliability. Firebase and Amplitude process it as service providers for those purposes. We do not sell it or use it for advertising or ad personalization.",
    ],
  },
  {
    title: "Transmission, retention, and deletion",
    paragraphs: [
      "Analytics and diagnostic information is transmitted over encrypted connections to Firebase, Amplitude, or the relevant platform service. The game and local saves continue to work if you are offline or one of those services is unavailable.",
      "Firebase Crashlytics retains crash stack traces and related identifiers for 90 days before beginning deletion. Other analytics information is retained, deleted, or aggregated according to the retention settings and agreements for each service.",
      "To request access to or deletion of analytics or diagnostic information, contact us at the address below. Because the game has no account and uses pseudonymous installation identifiers, we may need additional information visible in the app to locate a record, and in some cases an individual record may not be technically identifiable.",
    ],
  },
  {
    title: "Children and policy changes",
    paragraphs: [
      "The game does not ask children for directly identifying information such as a name or contact details and does not show advertising. The product-use and diagnostic information described above may be processed for the same purposes on iOS and Android.",
      "If the information we process or our purposes change, we will update this page first and communicate material changes through an app update description or another appropriate method.",
    ],
  },
];

export default function EnglishPrivacyPage() {
  return (
    <main className="legal" lang="en">
      <header className="legal-head">
        <p className="legal-kicker">Privacy Policy</p>
        <h1>How we handle game data and quality information</h1>
        <p className="legal-lede">
          This policy applies to Mound Reborn on iOS and Android. Last updated {lastUpdated}.
        </p>
        <p><a href="/privacy" lang="ko">한국어로 보기</a></p>
      </header>

      <div className="legal-body">
        {sections.map((section) => (
          <section key={section.title}>
            <h2>{section.title}</h2>
            {section.paragraphs.map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
          </section>
        ))}

        <section>
          <h2>External services</h2>
          <p>
            You can learn more in the{" "}
            <a href="https://firebase.google.com/support/privacy/">Firebase privacy documentation</a>{" "}
            and the{" "}
            <a href="https://amplitude.com/security-and-privacy">Amplitude security and privacy documentation</a>.
          </p>
        </section>

        <section>
          <h2>Contact</h2>
          <p>
            For questions about this policy, email{" "}
            <a href="mailto:kimsol1134@gmail.com">kimsol1134@gmail.com</a>.
          </p>
        </section>
      </div>
    </main>
  );
}
